// Game-owned labels travel with the Zuma package, including offline updates.
const en = {
  title:'ZUMA', subtitle:'TEMPLE ADVENTURE', score:'SCORE', level:'TEMPLE', lives:'LIVES',
  pause:'Pause', resume:'Continue', exit:'Save & exit', help:'How to play', close:'Back',
  swap:'SWAP', next:'NEXT', sound:'Sound', muted:'Sound off', aim:'Hold to aim · Release to fire',
  rotate:'Turn your phone sideways for a wider view', clear:'Clear the remaining marbles', target:'Fill the meter to stop new marbles',
  paused:'Take a breath', pausedText:'Your temple is safe. Continue when you are ready.',
  complete:'TEMPLE CLEARED', nextLevel:'Next temple', lost:'One more chance', retry:'Try this temple again',
  gameOver:'ADVENTURE COMPLETE', finish:'See results', points:'points', combo:'COMBO', chain:'CHAIN', gap:'GAP SHOT',
  coin:'GOLD COIN', bomb:'EXPLOSION', slow:'SLOW DOWN', reverse:'REVERSE', accuracy:'PRECISION', ready:'ZUMA!',
  helpTitle:'Master the stone frog',
  helpBody:'Match 3 or more touching marbles of one color. Hold anywhere on the board to aim, then release to shoot. Tap the frog or SWAP to exchange your two marbles. Matching ends pull together across a gap and can trigger another match. Fill the gold meter, then clear every remaining marble. Shoot coins and match marked marbles to activate explosion, slow, reverse or precision. You have three lives.',
  temples:['Jade Courtyard','Sunken Sanctuary','Serpent Passage','Moonlit Ruins','Golden Labyrinth','Sun Temple'],
};
const labels = {
  en,
  'zh-CN':{title:'祖玛',subtitle:'神庙冒险',score:'分数',level:'神庙',lives:'生命',pause:'暂停',resume:'继续冒险',exit:'保存并退出',help:'玩法',close:'返回',swap:'换球',next:'下一颗',sound:'音效',muted:'静音',aim:'按住瞄准 · 松手发射',rotate:'横持手机，获得更宽阔的棋盘',clear:'清空剩余彩珠即可过关',target:'填满能量槽，停止新珠进入',paused:'稍作休息',pausedText:'神庙已暂停，准备好后继续冒险。',complete:'神庙通关',nextLevel:'进入下一关',lost:'还有机会',retry:'再挑战这一关',gameOver:'冒险结束',finish:'查看成绩',points:'分',combo:'连锁',chain:'连续命中',gap:'穿隙射击',coin:'金币',bomb:'爆炸',slow:'减速',reverse:'倒退',accuracy:'精准瞄准',ready:'祖玛！',helpTitle:'掌握石蛙的力量',helpBody:'让相邻的 3 颗及以上同色彩珠相碰即可消除。按住棋盘任意位置瞄准，拖动调整方向，松手发射；轻点青蛙或“换球”交换当前珠和下一颗。断口两端同色时会吸回，接合后可继续连锁。填满金色能量槽后，清空剩余彩珠便能过关。射中金币可加分；消除带标记的彩珠会触发爆炸、减速、倒退或精准瞄准。每次冒险有 3 条生命。',temples:['翡翠庭院','沉落圣殿','灵蛇回廊','月影遗迹','黄金迷宫','太阳神殿']},
  'zh-TW':{title:'祖瑪',subtitle:'神廟冒險',score:'分數',level:'神廟',lives:'生命',pause:'暫停',resume:'繼續冒險',exit:'儲存並退出',help:'玩法',close:'返回',swap:'換球',next:'下一顆',sound:'音效',muted:'靜音',aim:'按住瞄準 · 放開發射',rotate:'橫持手機，獲得更寬闊的棋盤',clear:'清空剩餘彩珠即可過關',target:'填滿能量槽，停止新珠進入',paused:'稍作休息',pausedText:'神廟已暫停，準備好後繼續冒險。',complete:'神廟通關',nextLevel:'進入下一關',lost:'還有機會',retry:'再挑戰這一關',gameOver:'冒險結束',finish:'查看成績',points:'分',combo:'連鎖',chain:'連續命中',gap:'穿隙射擊',coin:'金幣',bomb:'爆炸',slow:'減速',reverse:'倒退',accuracy:'精準瞄準',ready:'祖瑪！',helpTitle:'掌握石蛙的力量',helpBody:'讓相鄰的 3 顆以上同色彩珠相碰即可消除。按住棋盤瞄準，拖動調整方向，放開發射；點青蛙或「換球」交換彩珠。斷口兩端同色時會吸回並觸發連鎖。填滿金色能量槽後，清空剩餘彩珠即可過關。射中金幣可加分；消除帶標記的彩珠可觸發爆炸、減速、倒退或精準瞄準。每次冒險有 3 條生命。',temples:['翡翠庭院','沉落聖殿','靈蛇迴廊','月影遺跡','黃金迷宮','太陽神殿']},
  ja:{title:'ズマ',subtitle:'神殿の冒険',score:'スコア',level:'神殿',lives:'ライフ',pause:'一時停止',resume:'冒険を続ける',exit:'保存して終了',help:'遊び方',close:'戻る',swap:'交換',next:'次の玉',sound:'効果音',muted:'消音',aim:'押して狙う · 離して発射',rotate:'横向きにすると盤面が広がります',clear:'残りの玉をすべて消そう',target:'ゲージを満たすと玉の追加が止まります',paused:'ひと休み',pausedText:'神殿は一時停止中です。',complete:'神殿クリア',nextLevel:'次の神殿',lost:'まだチャンスはある',retry:'この神殿を再挑戦',gameOver:'冒険終了',finish:'結果を見る',points:'点',combo:'連鎖',chain:'連続成功',gap:'隙間ショット',coin:'金貨',bomb:'爆発',slow:'スロー',reverse:'逆戻り',accuracy:'精密照準',ready:'ズマ！',helpTitle:'石のカエルを使いこなそう',helpBody:'同じ色の玉を3個以上つなげて消します。盤面を押して狙い、指を離して発射。カエルか交換ボタンをタップすると玉を交換できます。隙間の両端が同じ色なら引き寄せ合い、連鎖が起きます。ゲージを満たして残りの玉を消すとクリア。金貨を撃ち、印付きの玉を消して爆発・スロー・逆戻り・精密照準を使いましょう。ライフは3つです。',temples:['翡翠の庭','沈んだ聖堂','蛇の回廊','月影の遺跡','黄金の迷宮','太陽の神殿']},
  ko:{title:'주마',subtitle:'신전 모험',score:'점수',level:'신전',lives:'생명',pause:'일시 정지',resume:'계속하기',exit:'저장 후 나가기',help:'게임 방법',close:'돌아가기',swap:'교체',next:'다음 구슬',sound:'효과음',muted:'음소거',aim:'누르고 조준 · 놓으면 발사',rotate:'가로로 돌리면 보드가 넓어집니다',clear:'남은 구슬을 모두 없애세요',target:'게이지를 채우면 새 구슬이 멈춥니다',paused:'잠깐 쉬어 가요',pausedText:'신전이 일시 정지되었습니다.',complete:'신전 클리어',nextLevel:'다음 신전',lost:'아직 기회가 있어요',retry:'이 신전 다시 도전',gameOver:'모험 종료',finish:'결과 보기',points:'점',combo:'연쇄',chain:'연속 성공',gap:'틈새 사격',coin:'금화',bomb:'폭발',slow:'감속',reverse:'역행',accuracy:'정밀 조준',ready:'주마!',helpTitle:'돌개구리의 힘을 익히세요',helpBody:'같은 색 구슬을 3개 이상 이어 없애세요. 보드를 누르고 조준한 뒤 놓으면 발사합니다. 개구리나 교체 버튼을 누르면 구슬을 바꿉니다. 틈 양쪽의 색이 같으면 끌려와 연쇄가 일어납니다. 게이지를 채운 뒤 남은 구슬을 모두 없애면 통과합니다. 금화를 맞히고 표시된 구슬을 없애 폭발, 감속, 역행, 정밀 조준을 얻으세요. 생명은 3개입니다.',temples:['비취 정원','가라앉은 성소','뱀의 회랑','달빛 유적','황금 미궁','태양 신전']},
};
export function zumaLabels(locale) { return {...en,...(labels[locale] || en)}; }
