import test from 'node:test';
import assert from 'node:assert/strict';
import {CHECKPOINT_KEYS,captureStorage,restoreCheckpoint,gameContentMetadata,requireCompatibleSave,readContentState,confirmContentReady} from '../standalone/content-state.js';
import {changedPackages} from '../standalone/game-updates.js';
function store(){const map=new Map();return {map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};}
test('checkpoint only captures five game keys, preserves exact bytes and restores them',()=>{const s=store();s.setItem(CHECKPOINT_KEYS[0],'{ "theme": "pink" }');s.setItem('unrelated','keep');const before=captureStorage(s);s.setItem(CHECKPOINT_KEYS[0],'{}');restoreCheckpoint(s,before);assert.equal(s.getItem(CHECKPOINT_KEYS[0]),'{ "theme": "pink" }');assert.equal(s.getItem('unrelated'),'keep');assert.equal(s.getItem(CHECKPOINT_KEYS[1]),null);});
test('invalid checkpoint is rejected before any storage mutation',()=>{const s=store();s.setItem(CHECKPOINT_KEYS[0],'{}');const before=captureStorage(s);assert.throws(()=>restoreCheckpoint(s,{...before,evil:'{}'}));assert.throws(()=>restoreCheckpoint(s,{...before,[CHECKPOINT_KEYS[1]]:'broken'}));assert.deepEqual(captureStorage(s),before);});
test('failed write restores the pre-operation checkpoint instead of leaving mixed data',()=>{const s=store();for(const key of CHECKPOINT_KEYS)s.setItem(key,'{"old":true}');const before=captureStorage(s),put=s.setItem;let fails=true;s.setItem=(key,value)=>{if(fails&&key===CHECKPOINT_KEYS[2]){fails=false;throw Error('disk full');}put(key,value);};assert.throws(()=>restoreCheckpoint(s,Object.fromEntries(CHECKPOINT_KEYS.map(key=>[key,'{}']))),/disk full/);assert.deepEqual(captureStorage(s),before);});
test('per-game metadata locks original versions and never overrides game-native rules fields',()=>{const state={activeSnapshotId:'abc',active:{runtimeApi:1,packages:[{id:'art.match3',version:'2.1.0'}],games:{match3:{version:'1.3.0',saveSchema:3,art:['art.match3']}}}};const metadata=gameContentMetadata('match3',state);state.active.games.match3.version='1.4.0';assert.equal(metadata.gameVersion,'1.3.0');assert.deepEqual(metadata.artVersions,{'art.match3':'2.1.0'});assert.equal(metadata.saveSchema,3);assert.equal(metadata.rulesVersion,undefined);assert.doesNotThrow(()=>requireCompatibleSave({rulesVersion:3},metadata));assert.throws(()=>requireCompatibleSave({_content:{runtimeApi:1,saveSchema:4}},metadata));});
test('native bridge accepts both direct and asynchronous state; previews have no updater',async()=>{assert.equal(await readContentState({}),null);for(const getContentState of [()=>'{"activeSnapshotId":"a"}',async()=>'{"activeSnapshotId":"a"}'])assert.equal((await readContentState({NativeBridge:{getContentState}})).activeSnapshotId,'a');});
test('update preview only lists changed package digests',()=>{assert.deepEqual(changedPackages({active:{packages:[{id:'core',sha256:'a'},{id:'game.match3',sha256:'b'}]},candidate:{packages:[{id:'core',sha256:'a'},{id:'game.match3',sha256:'c'}]}}),[{id:'game.match3',sha256:'c'}]);});
test('accepted health job is not treated as a committed marker',async()=>{let reads=0;const host={NativeBridge:{reportGameContentReady:()=>'{"accepted":true}',getContentState:()=>JSON.stringify({activeSnapshotId:'new',bootHealthy:++reads>1})}};await confirmContentReady(host,'new');assert.equal(reads,2);await assert.rejects(()=>readContentState({NativeBridge:{getContentState:()=>'{"error":"bad restore"}'}}),/bad restore/);});
