// Run against a dedicated headless development browser, never a personal profile.
// node tests/standalone-browser.mjs [CDP port] [local page URL]
import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';

const port = Number(process.argv[2] || 9348);
const url = process.argv[3] || 'http://127.0.0.1:8768/standalone/index.html';
if (!url.startsWith('http://127.0.0.1:')) throw Error('This test is restricted to a local development server.');
const tabs = await (await fetch(`http://127.0.0.1:${port}/json`)).json();
const tab = tabs.find(t => t.type === 'page' && (t.url === 'about:blank' || t.url.startsWith('http://127.0.0.1:8768/')));
if (!tab) throw Error('No isolated development tab');
const socket = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((resolve,reject) => {socket.onopen=resolve;socket.onerror=reject;});
let nextId=0; const pending=new Map(), errors=[], requests=[];
socket.onmessage=e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);} else if(m.method==='Runtime.exceptionThrown') errors.push(m.params.exceptionDetails); else if(m.method==='Network.requestWillBeSent') requests.push(m.params.request.url);};
const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++nextId,{resolve,reject});socket.send(JSON.stringify({id:nextId,method,params}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const until=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await wait(100);}throw Error('Timeout '+expression);};
const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
const checks=[];
try {
  await send('Runtime.enable'); await send('Network.enable'); await send('Page.enable');
  await send('Emulation.setDeviceMetricsOverride',{width:412,height:820,deviceScaleFactor:2.625,mobile:true});
  await send('Page.navigate',{url}); await until('!!window.wanbaApp');
  await evaluate('localStorage.clear();localStorage.setItem("wanba_locale_v1","zh-CN")'); await send('Page.reload'); await until('!!window.wanbaApp');
  assert.deepEqual(await evaluate('[typeof jQuery,typeof $,typeof SillyTavern,typeof wbTest]'),['undefined','undefined','undefined','undefined']);
  assert.equal(await evaluate('wanbaApp.inspect().games.length'),37);
  assert.deepEqual(await evaluate('[...document.querySelectorAll(".wb-tab")].map(e=>e.dataset.tab)'),['single','double','settings']);
  assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'),true);
  checks.push('starts all 37-game catalog without host globals or test hooks');
  await click('[data-tab="settings"]');
  assert.equal(await evaluate('!!document.querySelector("#wb-api-url,#wb-companion-toggle,#wb-message-notify")'),false);
  await evaluate('document.querySelector("#wb-theme").value="cyber";document.querySelector("#wb-theme").dispatchEvent(new Event("change"))');
  assert.equal(await evaluate('wanbaApp.inspect().theme'),'cyber');
  assert.equal(await evaluate('document.querySelector("#wanba-toast").hidden'),false);
  await evaluate('window.NativeBridge={saveBackup:(filename,text)=>{window.capturedBackup={filename,data:JSON.parse(text)}}}');
  await click('#wb-export-data');
  const backup=await evaluate('capturedBackup');
  assert.equal(backup.data.app,'玩吧'); assert.ok(backup.filename.startsWith('玩吧-备份'));
  assert.deepEqual(Object.keys(backup.data.items).sort(),['wanbanXiaowu_settings_v1','wanbanXiaowu_scores_v1','wanbanXiaowu_progress_v1','wanbanXiaowu_records_v1','wanbanXiaowu_sudokuState_v1'].sort());
  checks.push('offline settings change, visible toast, native backup export contract');
  await evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File(['invalid JSON'],'invalid.json',{type:'application/json'}));const input=document.querySelector('#wb-import-file');input.files=dt.files;input.dispatchEvent(new Event('change'));})()`);
  await until('document.querySelector("#wanba-toast").textContent.includes("导入失败")');
  assert.equal(await evaluate('wanbaApp.inspect().theme'),'cyber');
  await evaluate(`(()=>{const data={items:{wanbanXiaowu_settings_v1:{theme:'night',companion:true,petDesktopEnabled:true,messageNotify:true,selectedFont:'remote',customFonts:[{name:'remote',url:'https://example.test/font'}]}}};const dt=new DataTransfer();dt.items.add(new File([JSON.stringify(data)],'legacy.json',{type:'application/json'}));const input=document.querySelector('#wb-import-file');input.files=dt.files;input.dispatchEvent(new Event('change'));})()`);
  await until('!!document.querySelector("#wb-confirm-ok")');
  assert.equal(await evaluate('wanbaApp.inspect().theme'),'cyber');
  await click('#wb-confirm-ok');
  assert.equal(await evaluate('wanbaApp.inspect().theme'),'night');
  assert.equal(await evaluate('document.querySelector("#wanbanXiaowu-popup").classList.contains("wb-night")'),true);
  assert.equal(await evaluate('JSON.parse(localStorage.getItem("wanbanXiaowu_settings_v1")).companion'),false);
  checks.push('FileReader rejects invalid JSON; confirmed legacy import updates theme and enforces offline capabilities');
  await evaluate('wanbaApp.back()'); await click('[data-game="freecell"]'); await click('#wb-start-cover-btn');
  await until('wanbaApp.inspect().started');
  await evaluate('wanbaApp.pause()'); assert.equal(await evaluate('wanbaApp.inspect().paused'),true);
  const saved=await evaluate('wanbaApp.inspect().controller');
  await click('#wb-pause'); await until('!!document.querySelector("#wb-resume-mask")');
  await evaluate('wanbaApp.pause()'); await wait(3300); assert.equal(await evaluate('wanbaApp.inspect().paused'),true);
  await evaluate('wanbaApp.back()'); await click('[data-game="freecell"]'); await until('!!document.querySelector("#wb-progress-continue")');
  await click('#wb-progress-continue'); await until('wanbaApp.inspect().started');
  assert.deepEqual(await evaluate('wanbaApp.inspect().controller.columns'),saved.columns);
  await evaluate('wanbaApp.pause();wanbaApp.back()');
  checks.push('pause freezes, cancels resume countdown, preserves exact FreeCell lobby state');
  await click('[data-tab="double"]'); await click('[data-game="wordguess"]'); await click('#wb-start-cover-btn');
  await until('wanbaApp.inspect().started && !!document.querySelector("#wb-word-input")');
  assert.equal(await evaluate('!!document.querySelector("#wb-word-bank-source-inline")'),false);
  await evaluate('wanbaApp.pause();wanbaApp.back()');
  checks.push('word guessing uses packaged offline bank');
  await click('[data-tab="single"]'); await click('[data-game="pinball"]'); await click('#wb-start-cover-btn');
  await until('!!document.querySelector(".wb-cadet-frame")?.contentWindow?.cadetHost?.snapshot()?.ready');
  await wait(500); await evaluate('wanbaApp.pause()');
  const tick = await evaluate('document.querySelector(".wb-cadet-frame").contentWindow.cadetHost.snapshot().ticks');
  await wait(400);
  assert.equal(await evaluate('document.querySelector(".wb-cadet-frame").contentWindow.cadetHost.snapshot().ticks'),tick);
  const display = await evaluate('document.querySelector(".wb-cadet-frame").contentWindow.cadetHost.displayInspection()');
  assert.ok(display.frames > 0); assert.equal(display.mode,'hd');
  const pinballShot = await send('Page.captureScreenshot',{format:'png'});
  writeFileSync('/private/tmp/wanba-standalone-pinball.png',Buffer.from(pinballShot.data,'base64'));
  await evaluate('wanbaApp.back()');
  checks.push('packaged WASM and HD display load under CSP; native pause immediately freezes ticks');
  assert.equal(requests.filter(u=>/^https?:/.test(u)&&!u.startsWith('http://127.0.0.1:8768/')).length,0);
  assert.deepEqual(errors,[]);
  const catalogShot = await send('Page.captureScreenshot',{format:'png'});
  writeFileSync('/private/tmp/wanba-standalone-catalog.png',Buffer.from(catalogShot.data,'base64'));
  await click('[data-tab="settings"]');
  const settingsShot = await send('Page.captureScreenshot',{format:'png'});
  writeFileSync('/private/tmp/wanba-standalone-settings.png',Buffer.from(settingsShot.data,'base64'));
  console.log(JSON.stringify({passed:true,checks,requests:requests.length},null,2));
} catch(error) {
  const shot=await send('Page.captureScreenshot',{format:'png'});writeFileSync('/private/tmp/wanba-standalone-failure.png',Buffer.from(shot.data,'base64'));
  console.error(JSON.stringify({passed:false,checks,error:error.stack,errors},null,2));process.exitCode=1;
} finally {socket.close();}
