// Dedicated local browser only. No production mutation hooks; all play uses real input events.
import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
const port=Number(process.env.CDP_PORT||9357),url=process.env.SUDOKU_URL||'http://127.0.0.1:8877/standalone/index.html';
const out=process.env.QA_OUT||'.local/qa-sudoku-browser';mkdirSync(out,{recursive:true});
const tabs=await(await fetch(`http://127.0.0.1:${port}/json`)).json(),tab=tabs.find(t=>t.url.startsWith(new URL(url).origin));
if(!tab)throw Error('Dedicated browser tab unavailable');
const socket=new WebSocket(tab.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});
let id=0;const pending=new Map(),errors=[],checks=[];
socket.onmessage=e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);};
const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});socket.send(JSON.stringify({id:n,method,params}));});
const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const until=async(expression,timeout=15000)=>{const end=Date.now()+timeout;while(Date.now()<end){if(await evaluate(expression))return;await wait(100);}throw Error('Timeout: '+expression);};
const click=async selector=>{await evaluate(`document.querySelector(${JSON.stringify(selector)})?.scrollIntoView({block:"center"})`);await wait(100);const rect=await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)}),r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);await touch(rect.x,rect.y);};
async function touch(x,y,dx=0,dy=0){await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});if(dx||dy){await wait(90);await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx,y:y+dy}]});}await wait(50);await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(90);}
const screenshot=async name=>{const r=await send('Page.captureScreenshot',{format:'png'});writeFileSync(`${out}/${name}.png`,Buffer.from(r.data,'base64'));};
const state=()=>evaluate('wanbaApp.inspect().controller');
const gameState=()=>state();
const cell=i=>'[data-sudoku-cell][data-i="'+i+'"]';
const keyboard=async(key,code=key,modifiers=0)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key,code,modifiers});await send('Input.dispatchKeyEvent',{type:'keyUp',key,code,modifiers});await wait(120);};
const geometry=()=>evaluate(`(()=>{const p=document.querySelector('#wb-sudoku-fullscreen'),els=[p.querySelector('.sd-grid'),...p.querySelectorAll('.sd-head button,.sd-tools button,.sd-keypad button,.sd-bottom button')];return els.map(e=>{const r=e.getBoundingClientRect();return {id:e.id,x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom};});})()`);
const visible=async()=>{const g=await geometry(),v=await evaluate('({w:innerWidth,h:innerHeight})');for(const r of g){assert(r.w>0&&r.h>0,JSON.stringify(r));assert(r.x>=0&&r.y>=0&&r.right<=v.w+1&&r.bottom<=v.h+1,JSON.stringify({r,v}));}return g;};
const begin=async(difficulty='easy')=>{await evaluate('wanbaApp.back()');await click('[data-tab="single"]');await click('[data-game="sudoku"]');await click('#wb-start-cover-btn');await click('[data-choice="'+difficulty+'"]');await until('!!document.querySelector("#wb-sudoku-fullscreen")');await wait(300);};
const reload=async()=>{await send('Page.reload');await wait(500);await until('!!window.wanbaApp');};
const resume=async()=>{if(!await evaluate('!!document.querySelector("#wb-progress-continue")')){await evaluate('wanbaApp.back()');await click('[data-tab="single"]');await click('[data-game="sudoku"]');}await until('!!document.querySelector("#wb-progress-continue")');await click('#wb-progress-continue');await until('!!document.querySelector("#wb-sudoku-fullscreen")');await wait(180);};
try{
 await send('Runtime.enable');await send('Network.enable');await send('Network.setCacheDisabled',{cacheDisabled:true});await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await send('Emulation.setTouchEmulationEnabled',{enabled:true});await send('Page.navigate',{url});await wait(500);await until('!!window.wanbaApp');
 // Only this isolated QA browser profile is seeded/cleared, never a user device.
 await evaluate(`localStorage.removeItem('wanbanXiaowu_progress_v1');localStorage.removeItem('wanbanXiaowu_records_v1');localStorage.setItem('wanba_locale_v1','zh-CN');localStorage.setItem('wanbanXiaowu_settings_v1',JSON.stringify({theme:'day',companion:false}));`);await reload();await begin();
 assert.equal((await state()).view.uniquePuzzle,true);assert.equal((await state()).view.renderer,'dom');await visible();
 const start=await state(),empty=start.puzzle.findIndex(n=>!n),fixed=start.puzzle.findIndex(Boolean),digit=start.solution[empty];
 await evaluate('window.__sudokuCells=[...document.querySelectorAll("[data-sudoku-cell]")]');
 await click(cell(fixed));await click('#wb-sudoku-number-'+(start.puzzle[fixed]%9+1));assert.equal((await state()).grid[fixed],start.puzzle[fixed]);
 await click(cell(empty));await click('#wb-sudoku-notes');await click('#wb-sudoku-number-'+digit);assert.equal((await state()).notes[empty],1<<(digit-1));assert.equal((await state()).grid[empty],0);
 await click('#wb-sudoku-undo');assert.equal((await state()).notes[empty],0);await click('#wb-sudoku-redo');assert.equal((await state()).notes[empty],1<<(digit-1));await screenshot('portrait-notes');
 await click('#wb-sudoku-notes');await click('#wb-sudoku-number-'+digit);assert.equal((await state()).grid[empty],digit);assert.equal((await state()).notes[empty],0);await click('#wb-sudoku-undo');assert.equal((await state()).grid[empty],0);assert.equal((await state()).notes[empty],1<<(digit-1));await click('#wb-sudoku-redo');
 checks.push('Given cells immutable; 3x3 notes, fill, erase and atomic undo/redo use real touch input');
 await click('#wb-sudoku-auto-notes');await click('#wb-sudoku-confirm-notes');const auto=await state();assert(auto.notes.some(Boolean));await click('#wb-sudoku-undo');assert.equal((await state()).notes.filter(Boolean).length,0);await click('#wb-sudoku-redo');assert.deepEqual((await state()).notes,auto.notes);await screenshot('auto-notes');
 await click('#wb-sudoku-hint');const preview=await state();assert.equal(preview.hints,1);await screenshot('logical-hint');await click('#wb-sudoku-dialog-close');await click('#wb-sudoku-hint');assert.equal((await state()).hints,1);await click('#wb-sudoku-apply-hint');assert.equal((await state()).hints,1);assert.equal((await state()).grid.filter(Boolean).length,auto.grid.filter(Boolean).length+1);
 checks.push('Auto candidates one undo step; explained hint preview charges once, repeated preview/apply do not double charge');
 await wait(300);const rendered=(await state()).view.renders;await wait(1300);assert.equal((await state()).view.renders,rendered);assert(await evaluate('window.__sudokuCells.every((e,i)=>e===document.querySelectorAll("[data-sudoku-cell]")[i])'));checks.push('Board DOM nodes retained; idle board renders zero frames while clock advances');
 await click('#wb-sudoku-pause');const paused=await state(),clockPaused=await evaluate('document.querySelector("#wb-sudoku-time").textContent');await keyboard('7','Digit7');await wait(1100);assert.deepEqual((await state()).grid,paused.grid);assert.deepEqual((await state()).notes,paused.notes);assert.equal(await evaluate('document.querySelector("#wb-sudoku-time").textContent'),clockPaused);assert.equal(await evaluate('getComputedStyle(document.querySelector("#wb-sudoku-board")).visibility'),'hidden');await screenshot('pause');await click('#wb-sudoku-resume');
 await click('#wb-sudoku-settings');await click('#wb-sudoku-option-number-first');await click('#wb-sudoku-option-check');await click('#wb-sudoku-dialog-close');let s=await state(),target=s.grid.findIndex(n=>!n);await click('#wb-sudoku-number-'+s.solution[target]);await click(cell(target));assert.equal((await state()).grid[target],s.solution[target]);
 await click('#wb-sudoku-settings');await click('#wb-sudoku-option-number-first');await click('#wb-sudoku-dialog-close');
 s=await state();target=s.grid.findIndex(n=>!n);await click(cell(target));const wrong=s.solution[target]%9+1;await click('#wb-sudoku-number-'+wrong);assert.equal(await evaluate('document.querySelector('+JSON.stringify(cell(target))+').getAttribute("aria-invalid")'),'true');await click('#wb-sudoku-undo');
 checks.push('Pause hides board, freezes time and blocks keyboard; settings and number-first input work; errors have non-color indicators');
 const saved=await state();await click('#wb-sudoku-pause');await click('#wb-sudoku-save-exit');await reload();await resume();s=await state();for(const k of ['grid','notes','history','future','hints','inputMode','sudokuOptions'])assert.deepEqual(s[k],saved[k],k+' restored');await click('#wb-sudoku-undo');await click('#wb-sudoku-redo');assert.deepEqual((await state()).grid,saved.grid);checks.push('Cold page reload restores puzzle, grid, notes, settings and undo/redo history');
 for(const [w,h,name] of [[844,390,'landscape'],[320,640,'narrow'],[390,844,'portrait']]){await send('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:2,mobile:true});await wait(400);await visible();assert.deepEqual((await state()).grid,saved.grid);await screenshot(name);}
 checks.push('Portrait390x844, narrow320x640 and landscape844x390 controls fully visible; rotation preserves state');
 // Play the remaining board using actual cell taps and keyboard digits, then verify persisted score.
 s=await state();for(let i=0;i<81;i++)if(!s.grid[i]){await click(cell(i));await keyboard(String(s.solution[i]),'Digit'+s.solution[i]);}
 await until('!document.querySelector("#wb-sudoku-fullscreen")');const records=await evaluate('JSON.parse(localStorage.getItem("wanbanXiaowu_records_v1")).sudoku');assert.equal(records.length,1);assert(records[0].result.score>0);assert.equal(records[0].details.hints,1);await screenshot('complete');checks.push({check:'Natural completed board records exactly once with nonzero structured score and hint count',score:records[0].result.score,hints:records[0].details.hints});
 // Same UI in all shipped languages and the dark theme, with isolated QA data only.
 for(const locale of ['zh-CN','zh-TW','en','ja','ko']){
  await evaluate(`wanbaApp.back();localStorage.removeItem('wanbanXiaowu_progress_v1');localStorage.setItem('wanba_locale_v1',${JSON.stringify(locale)});localStorage.setItem('wanbanXiaowu_settings_v1',JSON.stringify({theme:'night',companion:false}));`);await reload();await begin('expert');assert.equal((await state()).view.locale,locale);assert.equal((await state()).view.uniquePuzzle,true);const blanks=(await state()).grid.filter(n=>!n).length;assert(blanks>=59&&blanks<=61);await visible();await click('#wb-sudoku-settings');await screenshot(locale+'-settings');await click('#wb-sudoku-dialog-close');await screenshot(locale+'-night');await click('#wb-sudoku-pause');await click('#wb-sudoku-save-exit');
 }
 checks.push('All five languages, expert unique puzzles and night theme render without overflow');
 assert.deepEqual(errors,[]);const report={passed:true,checks,errors};writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
}catch(error){await screenshot('failure');const report={passed:false,checks,error:error.stack,errors,state:await state()};writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2)+'\n');console.error(JSON.stringify(report,null,2));process.exitCode=1;}finally{socket.close();}
