// Independently versioned game plugin. Keep imports relative to this immutable snapshot.
export const GAME_ID = 'turkey';
export const GAME_VERSION = '1.0.0';
export const HOST_API_VERSION = 1;
export const REQUIRED_ENV = Object.freeze(["clearProgress","gamePaused","getHostDocument","qs","qsa","saveProgress","scores","setScore","showGameOver","shuffleArray","speak"]);

// Host state is read through env getters on every callback, never snapshotted by destructuring.
export function createGame(env, state) {
  function startTurkey(state) {
    const box = env.qs('#wb-gamebox');
    const W=8,H=10,COLORS=['#FF7B7B','#FFD66B','#5FD1C8','#6CA8FF','#B28DFF'];
    const delay=ms=>new Promise(r=>setTimeout(r,ms));
    const rid=()=> 'tk_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
    const detailBase=()=>({ score:0, moves:0, clearedLines:0, maxClear:0, maxChain:0, maxCombo:0, noClearStreak:0, thunderUsed:0, stardustUsed:0, hammerUsed:0, toolsUsed:{}, noTool3000:false, clutch:false, amazingClear:false, clearAllCount:0, badLuck:false, toolsAll:false, badRows:[] });
    let st;
    function rowBlocks(row, opts={}){
      const top=highestRowFromBlocks(st?.blocks||[]), maxOcc=top<=2?5:7, needOne=opts.needOne || top<=1 || (st?.noOneRows||0)>=4;
      for(let tries=0;tries<80;tries++){
        const occ=Math.max(4, Math.min(maxOcc, 4+Math.floor(Math.random()*4))); let lengths=[]; let left=occ;
        if(needOne){ lengths.push(1); left--; }
        while(left>0 && lengths.length<4){ const maxLen=(st&&st.fourRows>=2)?Math.min(3,left):Math.min(4,left); const l=Math.min(left,1+Math.floor(Math.random()*maxLen)); lengths.push(l); left-=l; }
        if(left>0) continue; if(lengths.length<2 || lengths.length>4) continue;
        lengths=env.shuffleArray(lengths); const cells=Array(W).fill(0), blocks=[];
        for(const len of lengths){ let starts=[]; for(let c=0;c<=W-len;c++){ let ok=true; for(let k=0;k<len;k++) if(cells[c+k]) ok=false; if(ok) starts.push(c); } if(!starts.length) break; const col=starts[Math.floor(Math.random()*starts.length)]; for(let k=0;k<len;k++) cells[col+k]=1; blocks.push({id:rid(),row,col,len,color:COLORS[Math.floor(Math.random()*COLORS.length)],split:false}); }
        const used=cells.filter(Boolean).length; if(blocks.length===lengths.length && used>=1 && used<=7 && used<8 && (!needOne || blocks.some(b=>b.len===1))) return blocks;
      }
      return [{id:rid(),row,col:Math.floor(Math.random()*W),len:1,color:COLORS[Math.floor(Math.random()*COLORS.length)],split:false},{id:rid(),row,col:Math.floor(Math.random()*6),len:2,color:COLORS[Math.floor(Math.random()*COLORS.length)],split:false}];
    }
    function initial(){ let blocks=[], ones=0; for(let r=6;r<10;r++){ const bs=rowBlocks(r,{needOne:ones<2}); bs.forEach(b=>{ if(b.len===1) ones++; blocks.push(b); }); } return { blocks, score:0, moves:0, combo:0, tools:{thunder:3,stardust:3,hammer:3}, noOneRows:0, fourRows:0, details:detailBase(), seen:{}, over:false }; }
    st=state&&Array.isArray(state.blocks)?Object.assign(initial(),state):initial(); st.tools=Object.assign({thunder:3,stardust:3,hammer:3},st.tools||{}); st.details=Object.assign(detailBase(),st.details||{}); st.seen=st.seen||{}; normalizeStartBoard();
    let busy=false, over=false, selectedTool='', drag=null;
    box.innerHTML='<div class="wb-turkey"><div class="wb-turkey-top"><div class="wb-turkey-stats"><div class="wb-turkey-stat"><small>分数</small><b id="tk-score">0</b></div><div class="wb-turkey-stat"><small>消除</small><b id="tk-lines">0</b></div><div class="wb-turkey-stat"><small>连击</small><b id="tk-combo">0</b></div><div class="wb-turkey-stat"><small>移动</small><b id="tk-moves">0</b></div></div><div class="wb-turkey-danger"><div class="wb-turkey-danger-bar" id="tk-danger"></div><span id="tk-danger-text">安全</span></div><div class="wb-turkey-hint" id="tk-hint"></div></div><div class="wb-turkey-board" id="tk-board"></div><div class="wb-turkey-tools"><button class="wb-turkey-tool" data-tool="thunder">☁ 云雷<span class="badge" id="tk-thunder">3</span></button><button class="wb-turkey-tool" data-tool="stardust">✦ 星尘<span class="badge" id="tk-stardust">3</span></button><button class="wb-turkey-tool" data-tool="hammer">🔨 粉碎<span class="badge" id="tk-hammer">3</span></button></div></div>';
    env.speak('turkey','start'); draw(); save(); setTimeout(draw,50);
    env.qsa('.wb-turkey-tool',box).forEach(b=>b.onclick=()=>chooseTool(b.dataset.tool));
    function save(){ if(!over) env.saveProgress('turkey', Object.assign({}, st, { selectedTool:'' })); }
    function grid(ignore){ const g=Array.from({length:H},()=>Array(W).fill(null)); st.blocks.forEach(b=>{ if(b.id===ignore) return; for(let c=b.col;c<b.col+b.len;c++) if(b.row>=0&&b.row<H&&c>=0&&c<W) g[b.row][c]=b; }); return g; }
    function highestRowFromBlocks(bs){ return bs.length?Math.min(...bs.map(b=>b.row)):H; }
    function highest(){ return highestRowFromBlocks(st.blocks); }
    function canAt(b,col){ if(col<0||col+b.len>W) return false; const g=grid(b.id); for(let c=col;c<col+b.len;c++) if(g[b.row]?.[c]) return false; return true; }
    function faceFor(b){ const faces=['-v-','^v^','owo','-u-','>v<','^_^','ouo','-ᴗ-','>u<','uvu']; const n=String(b.id||'').split('').reduce((a,ch)=>a+ch.charCodeAt(0),0); return faces[n%faces.length]; }
    function chooseTool(t){ if(busy||over||env.gamePaused) return; if((st.tools[t]||0)<=0) return; selectedTool=selectedTool===t?'':t; draw(); }
    function toolHint(){ return selectedTool==='thunder'?'选择一个方块释放云雷':selectedTool==='stardust'?'选择一种颜色':selectedTool==='hammer'?'选择一个长度大于1的方块':''; }
    async function useTool(block){ if(!selectedTool||busy||over) return; if(selectedTool==='hammer'&&block.len<=1){ flash(block.id); return; } const danger=highest()<=2; busy=true; const t=selectedTool; selectedTool=''; st.tools[t]--; st.details.toolsUsed[t]=true; if(t==='thunder'){ st.details.thunderUsed++; env.speak('turkey','thunder'); const cx=block.col+Math.floor(block.len/2), cy=block.row; const doomed=st.blocks.filter(b=>{ for(let c=b.col;c<b.col+b.len;c++) if(Math.abs(c-cx)<=1&&Math.abs(b.row-cy)<=1) return true; return false; }); await animateThunder(doomed); st.blocks=st.blocks.filter(b=>!doomed.some(x=>x.id===b.id)); }
      if(t==='stardust'){ st.details.stardustUsed++; env.speak('turkey','stardust'); st.blocks=st.blocks.filter(b=>b.color!==block.color); }
      if(t==='hammer'){ st.details.hammerUsed++; env.speak('turkey','hammer'); st.blocks=st.blocks.filter(b=>b.id!==block.id); for(let c=0;c<block.len;c++) st.blocks.push({id:rid(),row:block.row,col:block.col+c,len:1,color:block.color,split:true}); }
      st.details.toolsAll=['thunder','stardust','hammer'].every(x=>st.details.toolsUsed[x]); await settle(false); await refillIfAlmostClear(); if(danger&&!over){ st.details.clutch=true; env.speak('turkey','danger_tool'); } draw(); save(); busy=false; }
    async function animateThunder(blocks){
      if(!blocks || !blocks.length) return;
      blocks.forEach(b=>{ const el=env.qs('.wb-turkey-block[data-id="'+b.id+'"]'); if(el) el.classList.add('shatter'); });
      const board=env.qs('#tk-board'), rect=board&&board.getBoundingClientRect(), cell=rect ? rect.width/W : 32;
      if(board) blocks.forEach(b=>{ for(let i=0;i<Math.max(4,b.len*3);i++){ const pt=env.getHostDocument().createElement('i'); pt.className='wb-turkey-particle'; pt.style.left=((b.col+Math.random()*b.len)*cell)+'px'; pt.style.top=((b.row+Math.random())*cell)+'px'; pt.style.setProperty('--c', b.color); pt.style.setProperty('--dx',(Math.random()*70-35)+'px'); pt.style.setProperty('--dy',(Math.random()*60-30)+'px'); board.appendChild(pt); setTimeout(()=>pt.remove(),460); } });
      await delay(340);
    }
    function gravity(){ let moved=false, any=true; while(any){ any=false; const bs=st.blocks.slice().sort((a,b)=>b.row-a.row); for(const b of bs){ if(b.row>=H-1) continue; const g=grid(b.id); let ok=true; for(let c=b.col;c<b.col+b.len;c++) if(g[b.row+1]?.[c]) ok=false; if(ok){ b.row++; moved=any=true; } } } return moved; }
    function fullRows(){ const g=grid(); const rows=[]; for(let r=0;r<H;r++) if(g[r].every(Boolean)) rows.push(r); return rows; }
    function occupiedRows(){ return new Set(st.blocks.map(b=>b.row).filter(r=>r>=0&&r<H)).size; }
    async function settle(countCombo){ let chain=0,total=0,maxR=0; gravity(); draw(); await delay(120); let rows=fullRows(); while(rows.length){ chain++; maxR=Math.max(maxR,rows.length); flashRows(rows); await delay(180); particleRows(rows); const set=new Set(rows); st.blocks=st.blocks.flatMap(b=>{ if(set.has(b.row)) return []; const overlap=[]; for(let c=b.col;c<b.col+b.len;c++) overlap.push(c); return [b]; }); const base=100*rows.length*rows.length, mult=1+(chain-1)*.5; st.score+=Math.round(base*mult); st.details.clearedLines+=rows.length; total+=rows.length; st.details.maxChain=Math.max(st.details.maxChain,chain); st.details.maxClear=Math.max(st.details.maxClear,rows.length); if(!st.seen.first_clear){st.seen.first_clear=1;env.speak('turkey','first_clear');} if(rows.length===2)env.speak('turkey','clear_2'); if(rows.length>=3)env.speak('turkey','clear_3'); if(chain>=3)env.speak('turkey','chain_3'); drawClearing(rows); await delay(210); gravity(); draw(); await delay(120); rows=fullRows(); }
      if(countCombo){ if(total){ st.combo++; st.details.noClearStreak=0; if(st.combo>=2){ st.score+=50*(st.combo-1); showCombo(st.combo); } if(st.combo>=5) env.speak('turkey','combo_5'); } else { st.combo=0; st.details.noClearStreak++; if(st.details.noClearStreak>=8) env.speak('turkey','no_clear_8'); } st.details.maxCombo=Math.max(st.details.maxCombo,st.combo); }
      if(st.score>=1000&&!st.seen.s1000){st.seen.s1000=1;env.speak('turkey','score_1000');} if(st.score>=5000&&!st.seen.s5000){st.seen.s5000=1;env.speak('turkey','score_5000');} if(st.score>=3000&&!Object.keys(st.details.toolsUsed||{}).length) st.details.noTool3000=true; return total; }
    function addGeneratedRow(row){ const bs=rowBlocks(row); const hasOne=bs.some(b=>b.len===1), occ=bs.reduce((a,b)=>a+b.len,0); st.noOneRows=hasOne?0:(st.noOneRows||0)+1; st.fourRows=bs.some(b=>b.len===4)?((st.fourRows||0)+1):0; const bad=!hasOne&&occ>=6; st.details.badRows=(st.details.badRows||[]).concat(bad?1:0).slice(-5); if(st.details.badRows.length===5&&st.details.badRows.filter(Boolean).length>=4) st.details.badLuck=true; st.blocks.push(...bs); }
    function addRow(){ const topBefore=highest(); st.blocks.forEach(b=>b.row--); const needOne=st.noOneRows>=4 || highest()<=1; const bs=rowBlocks(9,{needOne}); const hasOne=bs.some(b=>b.len===1), occ=bs.reduce((a,b)=>a+b.len,0); st.noOneRows=hasOne?0:(st.noOneRows||0)+1; st.fourRows=bs.some(b=>b.len===4)?((st.fourRows||0)+1):0; const bad=!hasOne&&occ>=6; st.details.badRows=(st.details.badRows||[]).concat(bad?1:0).slice(-5); if(st.details.badRows.length===5&&st.details.badRows.filter(Boolean).length>=4) st.details.badLuck=true; st.blocks.push(...bs); if(st.blocks.some(b=>b.row<0)){ gameOver(); return; } if(topBefore===0&&!over) env.speak('turkey','top_row'); else if(highest()<=2&&!st.seen.top3){ st.seen.top3=1; env.speak('turkey','top_3'); } }
    function normalizeStartBoard(){ gravity(); if(!st.blocks.length) for(let r=7;r<10;r++) addGeneratedRow(r); }
    function refillToThreeRows(){ gravity(); const rows=Array.from(new Set(st.blocks.map(b=>b.row))).sort((a,b)=>a-b); const keepRows=rows.slice(-1); if(keepRows.length){ st.blocks=st.blocks.filter(b=>b.row===keepRows[0]).map(b=>Object.assign(b,{row:7})); for(let r=8;r<10;r++) addGeneratedRow(r); } else { st.blocks=[]; for(let r=7;r<10;r++) addGeneratedRow(r); } }
    async function refillIfAlmostClear(){ if(over) return false; gravity(); if(occupiedRows()>1) return false; st.score+=300; st.details.amazingClear=true; st.details.clearAllCount=(st.details.clearAllCount||0)+1; showCombo('竟然全部消除 +300'); for(let attempt=0;attempt<3&&!over&&occupiedRows()<=1;attempt++){ refillToThreeRows(); draw(); await delay(360); await settle(false); gravity(); } if(!over&&occupiedRows()<=1){ refillToThreeRows(); draw(); } return true; }
    async function afterMove(wasTop){ const cleared=await settle(true); if(wasTop&&cleared>=2&&!over) st.details.clutch=true; const refilled=cleared ? await refillIfAlmostClear() : false; if(!refilled){ addRow(); draw(); if(!over){ await delay(360); await settle(false); await refillIfAlmostClear(); } } draw(); save(); }
    function gameOver(){ over=true; env.clearProgress('turkey'); env.setScore('turkey',Math.max(env.scores().turkey||0,st.score)); env.speak('turkey','gameover'); draw(); setTimeout(()=>env.showGameOver('turkey','游戏结束','本局分数：'+st.score+'分，消除'+st.details.clearedLines+'行',{outcome:'score',score:st.score},{details:Object.assign({},st.details,{score:st.score,moves:st.moves})}),350); }
    function draw(){ const board=env.qs('#tk-board'); if(!board) return; const rect=board.getBoundingClientRect(); const cell=(rect.width||320)/W; board.style.setProperty('--tk-cell',cell+'px'); const high=highest(), filled=high>=H?0:H-high, dangerClass=high<=0?'critical':high<=1?'danger':high<=3?'warn':'safe'; env.qs('#tk-danger').className='wb-turkey-danger-bar '+dangerClass; env.qs('#tk-danger').innerHTML=Array.from({length:10},(_,i)=>'<span class="'+(i<filled?'on':'')+'"></span>').join(''); env.qs('#tk-danger-text').textContent=dangerClass==='safe'?'安全':dangerClass==='warn'?'注意':'危险'; env.qs('#tk-hint').textContent=toolHint(); [['#tk-score',st.score],['#tk-lines',st.details.clearedLines],['#tk-combo',st.combo||0],['#tk-moves',st.moves||0],['#tk-thunder',st.tools.thunder],['#tk-stardust',st.tools.stardust],['#tk-hammer',st.tools.hammer]].forEach(([a,b])=>{const el=env.qs(a);if(el)el.textContent=b;}); env.qsa('.wb-turkey-tool',box).forEach(b=>{b.classList.toggle('active',selectedTool===b.dataset.tool); b.disabled=(st.tools[b.dataset.tool]||0)<=0;}); board.innerHTML=st.blocks.map(b=>'<div class="wb-turkey-block '+(selectedTool==='hammer'&&b.len<=1?'dim':'')+'" data-id="'+b.id+'" style="--c:'+b.color+';left:'+(b.col*cell+2)+'px;top:'+(b.row*cell+2)+'px;width:'+(b.len*cell-4)+'px"><span class="wb-turkey-face">'+faceFor(b)+'</span></div>').join(''); env.qsa('.wb-turkey-block',board).forEach(el=>{el.onclick=e=>{e.stopPropagation(); const b=st.blocks.find(x=>x.id===el.dataset.id); if(selectedTool&&b) useTool(b);}; el.onpointerdown=startDrag;}); }
    function startDrag(e){ if(busy||over||env.gamePaused||selectedTool) return; const b=st.blocks.find(x=>x.id===e.currentTarget.dataset.id); if(!b) return; e.preventDefault(); const board=env.qs('#tk-board'), rect=board.getBoundingClientRect(), cell=rect.width/W; drag={id:b.id,startX:e.clientX,startCol:b.col,col:b.col,cell}; e.currentTarget.classList.add('sel'); env.getHostDocument().addEventListener('pointermove',moveDrag,{passive:false}); env.getHostDocument().addEventListener('pointerup',endDrag,{once:true}); }
    function moveDrag(e){ if(!drag) return; e.preventDefault(); const b=st.blocks.find(x=>x.id===drag.id); if(!b) return; let col=drag.startCol+Math.round((e.clientX-drag.startX)/drag.cell); while(col<drag.col&&canAt(b,col)===false) col++; while(col>drag.col&&canAt(b,col)===false) col--; col=Math.max(0,Math.min(W-b.len,col)); drag.col=canAt(b,col)?col:drag.col; preview(b,drag.col,!canAt(b,col)); }
    async function endDrag(){ env.getHostDocument().removeEventListener('pointermove',moveDrag); const d=drag; drag=null; env.qsa('.wb-turkey-preview').forEach(x=>x.remove()); const b=st.blocks.find(x=>x.id===d?.id); if(!b){draw();return;} if(d.col===b.col||!canAt(b,d.col)){ draw(); return; } busy=true; const wasTop=highest()===0; b.col=d.col; st.moves++; st.details.moves=st.moves; draw(); await delay(130); await afterMove(wasTop); busy=false; }
    function preview(b,col,bad){ const board=env.qs('#tk-board'); if(!board) return; env.qsa('.wb-turkey-preview',board).forEach(x=>x.remove()); const cell=(board.getBoundingClientRect().width||320)/W; const el=env.getHostDocument().createElement('div'); el.className='wb-turkey-preview'+(bad?' bad':''); el.style.left=(col*cell+2)+'px'; el.style.top=(b.row*cell+2)+'px'; el.style.width=(b.len*cell-4)+'px'; board.appendChild(el); }
    function flash(id){ const el=env.qs('.wb-turkey-block[data-id="'+id+'"]'); if(el){el.classList.add('bad'); setTimeout(()=>el.classList.remove('bad'),180);} }
    function flashRows(rows){ const board=env.qs('#tk-board'), cell=(board.getBoundingClientRect().width||320)/W; rows.forEach(r=>{const el=env.getHostDocument().createElement('div'); el.className='wb-turkey-rowflash'; el.style.top=(r*cell)+'px'; board.appendChild(el); setTimeout(()=>el.remove(),220);}); }
    function particleRows(rows){ const board=env.qs('#tk-board'), cell=(board.getBoundingClientRect().width||320)/W; rows.forEach(r=>{for(let i=0;i<10;i++){const el=env.getHostDocument().createElement('i'); el.className='wb-turkey-particle'; el.style.left=(Math.random()*W*cell)+'px'; el.style.top=(r*cell+Math.random()*cell)+'px'; el.style.setProperty('--c',COLORS[Math.floor(Math.random()*COLORS.length)]); el.style.setProperty('--dx',(Math.random()*60-30)+'px'); el.style.setProperty('--dy',(Math.random()*50-25)+'px'); board.appendChild(el); setTimeout(()=>el.remove(),450);}}); }
    function drawClearing(rows){ const set=new Set(rows); env.qsa('.wb-turkey-block').forEach(el=>{const b=st.blocks.find(x=>x.id===el.dataset.id); if(b&&set.has(b.row)) el.classList.add('clear');}); }
    function showCombo(n){ const board=env.qs('#tk-board'); if(!board) return; const el=env.getHostDocument().createElement('div'); el.className='wb-turkey-combo'; el.textContent=typeof n==='number' ? 'COMBO ×'+n : String(n); board.appendChild(el); setTimeout(()=>el.remove(),850); }
  }
  startTurkey(state);
  return env.activeGameController || null;
}
