// Independently versioned game plugin. Keep imports relative to this immutable snapshot.
export const GAME_ID = 'blackjack';
export const GAME_VERSION = '1.0.0';
export const HOST_API_VERSION = 1;
export const REQUIRED_ENV = Object.freeze(["appendModalMask","clearProgress","currentGame","displayCharNameForGame","esc","findAvatar","gamePaused","getHostDocument","modalMaskClass","qs","qsa","saveProgress","scores","setScore","showGameOver","shuffleArray","speak"]);

// Host state is read through env getters on every callback, never snapshotted by destructuring.
export function createGame(env, state) {
  function startBlackjack(state) {
    const box=env.qs('#wb-gamebox'), charName=env.displayCharNameForGame('blackjack'), avatar=env.findAvatar();
    const LEVELS=[300,350,400,450,500,550,600,650], ERR=[.25,.20,.15,.12,.10,.07,.05,.03];
    const SUITS=['♠','♥','♣','♦'], RANKS=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
    const delay=ms=>new Promise(resolve=>{ const started=Date.now(); const tick=()=>{ if(env.currentGame!=='blackjack'||over) return resolve(); if(env.gamePaused) return setTimeout(tick,60); const left=ms-(Date.now()-started); if(left<=0) resolve(); else setTimeout(tick,Math.min(60,left)); }; tick(); });
    const baseState=()=>({level:1,total:0,userScore:0,charScore:0,user:[],char:[],deck:[],phase:'deal',target:300,userStreak:0,charStreak:0,maxStreak:0,round:0,tieBreak:false,personality:'冷静',peek:false,peekWin:false,lastDraw:null,protectReady:false,showPoints:false,lastWinner:'',firstMover:'user',userDone:false,charDone:false,reviveLeft:5,details:{score:0,level:1,wins:0,losses:0,ties:0,blackjacks:0,busts:0,charBusts:0,maxStreak:0,peekUsed:0,hintUsed:0,undoUsed:0,protectUsed:0,consecutiveBusts:0,charConsecutiveBusts:0,wonTiebreak:false,exact21:0,sixCard:false,reviveUsed:0,orderUserFirst:0,orderCharFirst:0}});
    let st=state ? Object.assign(baseState(), state) : baseState();
    const levelIndex = () => Math.min(8, Math.max(1, Number(st.level || 1))) - 1;
    st.level=Math.max(1,Number(st.level||1)); st.target=LEVELS[levelIndex()]; st.user=Array.isArray(st.user)?st.user:[]; st.char=Array.isArray(st.char)?st.char:[]; st.deck=Array.isArray(st.deck)?st.deck:[]; st.tools=Object.assign({hint:2,peek:1,undo:1,protect:st.level>=3?1:0}, st.tools || {}); st.details=Object.assign(baseState().details, st.details || {}); st.peek=false; st.lastDraw=null; st.reviveLeft=Math.max(0,Math.min(5,Number(st.reviveLeft == null ? 5 : st.reviveLeft))); st.firstMover=st.firstMover==='char'?'char':'user'; st.userDone=!!st.userDone; st.charDone=!!st.charDone;
    let busy=false, over=false, undoTimer=null, waitingUndo=false;
    box.innerHTML='<div class="wb-bj"><div class="wb-bj-top"><div class="wb-bj-title">21点 · <span id="bj-level">第1关</span><small id="bj-target">目标 300</small><button class="wb-bj-point-toggle" id="bj-point-toggle" type="button">显示点数</button></div><div class="wb-bj-total" id="bj-total">总分 0</div></div><div class="wb-bj-table"><div class="wb-bj-playerbar"><div class="wb-bj-avatar" id="bj-char-av">'+(avatar?'<img src="'+env.esc(avatar)+'" alt="">':env.esc(charName.slice(0,1)))+'</div><div class="wb-bj-name"><span id="bj-char-name">'+env.esc(charName)+'</span><small id="bj-personality">冷静</small><span class="wb-bj-streak" id="bj-char-streak"></span></div><div class="wb-bj-score" id="bj-char-score">0 / 300</div><div class="wb-bj-progress char"><span id="bj-char-fill"></span></div></div><div><div class="wb-bj-hand" id="bj-char-hand"></div><div class="wb-bj-points" id="bj-char-points">?</div></div><div class="wb-bj-mid"><div class="wb-bj-status" id="bj-status">准备发牌</div><div><div class="wb-bj-deck"><i></i><i></i><i></i></div><div style="text-align:center;margin-top:2px;">牌堆</div></div></div><div><div class="wb-bj-points" id="bj-user-points">0</div><div class="wb-bj-hand" id="bj-user-hand"></div></div><div class="wb-bj-playerbar user"><div class="wb-bj-name">你<span class="wb-bj-streak" id="bj-user-streak"></span></div><div class="wb-bj-score" id="bj-user-score">0 / 300</div><div class="wb-bj-progress user"><span id="bj-user-fill"></span></div></div><div class="wb-bj-tools"><button class="wb-bj-tool" data-tool="hint">💡 提示<span class="badge" id="bj-hint-left">2</span></button><button class="wb-bj-tool" data-tool="peek">👁 偷看<span class="badge" id="bj-peek-left">1</span></button><button class="wb-bj-tool" data-tool="undo">↩ 反悔<span class="badge" id="bj-undo-left">1</span></button><button class="wb-bj-tool" data-tool="protect">◇ 护牌<span class="badge" id="bj-protect-left">0</span></button></div><div class="wb-bj-actions"><button class="wb-bj-action wb-bj-hit" id="bj-hit">要牌</button><button class="wb-bj-action wb-bj-stand" id="bj-stand">停牌</button></div></div></div>';
    env.qs('#bj-hit').onclick=()=>playerHit(); env.qs('#bj-stand').onclick=()=>playerStand(); env.qs('#bj-point-toggle').onclick=()=>{ st.showPoints=!st.showPoints; draw(); }; env.qsa('.wb-bj-tool',box).forEach(b=>b.onclick=()=>useTool(b.dataset.tool));
    function newDeck(){ const a=[]; SUITS.forEach(s=>RANKS.forEach(r=>a.push({s,r,id:r+s}))); return env.shuffleArray(a); }
    function val(c){ return c.r==='A'?11:(/[JQK]/.test(c.r)?10:+c.r); }
    function handValue(h){ let total=0, aces=0; h.forEach(c=>{ total+=val(c); if(c.r==='A') aces++; }); let soft=aces>0; while(total>21&&aces){ total-=10; aces--; } soft=aces>0; return { total, soft, bust:total>21, bj:h.length===2&&total===21, exact21:total===21 }; }
    function scoreClass(v){ if(v.bust) return 'bust'; if(v.total===21) return 'gold'; if(v.total>=18) return 'good'; return ''; }
    function cardHTML(c, hidden){ if(hidden) return '<div class="wb-bj-card back"></div>'; const red=c.s==='♥'||c.s==='♦'; return '<div class="wb-bj-card '+(red?'red':'')+'"><div class="corner"><span>'+c.r+'</span><span>'+c.s+'</span></div><div class="pip">'+c.s+'</div></div>'; }
    function save(force){ if(!over) env.saveProgress('blackjack', Object.assign({}, st, { peek:false, lastDraw:null }), force ? { immediate:true } : undefined); }
    function draw(){ const target=st.target; const root=env.qs('.wb-bj',box); if(root) root.classList.toggle('show-points',!!st.showPoints); const toggle=env.qs('#bj-point-toggle',box); if(toggle){ toggle.textContent=st.showPoints?'隐藏点数':'显示点数'; toggle.classList.toggle('active',!!st.showPoints); } env.qs('#bj-level').textContent='第'+st.level+'关'; env.qs('#bj-target').textContent='目标 '+target; env.qs('#bj-total').textContent='总分 '+String(st.total).replace(/\B(?=(\d{3})+(?!\d))/g,','); env.qs('#bj-personality').textContent=st.level>=8?'认真起来了':(st.level>=3?st.personality:''); env.qs('#bj-char-score').textContent=st.charScore+' / '+target; env.qs('#bj-user-score').textContent=st.userScore+' / '+target; env.qs('#bj-char-fill').style.width=Math.min(100,st.charScore/target*100)+'%'; env.qs('#bj-user-fill').style.width=Math.min(100,st.userScore/target*100)+'%'; env.qs('#bj-user-streak').textContent=st.userStreak>=2?'🔥 ×'+st.userStreak:''; env.qs('#bj-char-streak').textContent=st.charStreak>=2?'🔥 ×'+st.charStreak:''; const reveal=st.phase==='char'||st.phase==='settle'||st.peek||st.charDone; env.qs('#bj-char-hand').innerHTML=st.char.map((c,i)=>cardHTML(c,i===1&&!reveal)).join(''); env.qs('#bj-user-hand').innerHTML=st.user.map(c=>cardHTML(c,false)).join(''); const uv=handValue(st.user), cv=handValue(st.char); const up=env.qs('#bj-user-points'), cp=env.qs('#bj-char-points'); up.textContent=uv.bust?'爆牌 '+uv.total:(uv.total===21?'21!':uv.total); up.className='wb-bj-points '+scoreClass(uv); cp.textContent=reveal?(cv.bust?'爆牌 '+cv.total:(cv.total===21?'21!':charName+' · '+cv.total)):(st.char[0]?'可见：'+handValue([st.char[0]]).total:'?'); cp.className='wb-bj-points '+(reveal?scoreClass(cv):''); const playerOn=st.phase==='player'&&!busy&&!over; env.qs('#bj-hit').disabled=!playerOn; env.qs('#bj-stand').disabled=!playerOn; [['hint',2],['peek',1],['undo',1],['protect',st.level>=3?1:0]].forEach(([k])=>{ const btn=env.qs('[data-tool="'+k+'"]',box); if(btn) btn.disabled=busy||over||(st.tools?.[k]||0)<=0||(k!=='undo'&&st.phase!=='player')||(k==='undo'&&!st.lastDraw)||(k==='protect'&&st.protectReady); const badge=env.qs('#bj-'+k+'-left'); if(badge) badge.textContent=st.tools?.[k]||0; }); const p=env.qs('[data-tool="protect"]',box); if(p) p.classList.toggle('ready',!!st.protectReady); if(!busy) save(); }
    function setStatus(t){ const el=env.qs('#bj-status'); if(el) el.textContent=t; }
    function toastMid(t){ const el=env.getHostDocument().createElement('div'); el.className='wb-bj-float'; el.textContent=t; env.qs('.wb-bj-table',box).appendChild(el); setTimeout(()=>el.remove(),1350); }
    function gain(who,text){ const el=env.getHostDocument().createElement('div'); el.className='wb-bj-gain'; el.textContent=text; env.qs(who==='user'?'#bj-user-score':'#bj-char-score',box).appendChild(el); setTimeout(()=>el.remove(),520); }
    function drawCard(to){ const c=st.deck.shift(); st[to].push(c); return c; }
    async function nextLevel(){ st.level++; startLevel(); }
    function personality(){ if(st.level<3) return '冷静'; if(st.level>=8){ const diff=st.charScore-st.userScore; return diff>150?'谨慎':(diff<-150?'冒险':'冷静'); } return ['谨慎','冷静','冒险'][Math.floor(Math.random()*3)]; }
    async function startLevel(){ st.target=LEVELS[levelIndex()]; st.userScore=0; st.charScore=0; st.userStreak=0; st.charStreak=0; st.round=0; st.tieBreak=false; st.personality=personality(); st.tools={hint:2,peek:1,undo:1,protect:st.level>=3?1:0}; st.protectReady=false; env.speak('blackjack','start'); await startRound(); }
    function chooseBlackjackOrder(){
      st.phase='order'; st.firstMover=''; setStatus('猜红黑决定本局先手'); draw(); save(true);
      return new Promise(resolve=>{
        const doc=env.getHostDocument(); const old=env.qs('#wb-bj-order-mask', doc); if(old) old.remove();
        const mask=doc.createElement('div'); mask.className=env.modalMaskClass(); mask.id='wb-bj-order-mask';
        mask.innerHTML='<div class="wb-modal"><div class="wb-modal-title">猜红黑决定先手</div><div style="margin-bottom:10px;line-height:1.8;">每小局开始前抽一张判定牌。猜中你先行动，猜错则'+env.esc(charName)+'先行动。</div><div class="wb-actions"><button class="wb-btn primary" id="wb-bj-guess-red">猜红色 ♥♦</button><button class="wb-btn" id="wb-bj-guess-black">猜黑色 ♠♣</button></div></div>';
        env.appendModalMask(mask);
        const pick=guess=>{ const card=st.deck.shift(); const red=card && (card.s==='♥'||card.s==='♦'); st.firstMover=((guess==='red')===red)?'user':'char'; if(st.firstMover==='user') st.details.orderUserFirst=(st.details.orderUserFirst||0)+1; else st.details.orderCharFirst=(st.details.orderCharFirst||0)+1; mask.remove(); toastMid('判定牌：'+card.r+card.s+'，'+(st.firstMover==='user'?'你先手':charName+'先手')); resolve(); };
        env.qs('#wb-bj-guess-red', mask).onclick=()=>pick('red');
        env.qs('#wb-bj-guess-black', mask).onclick=()=>pick('black');
      });
    }
    async function startRound(){ busy=true; st.round++; st.user=[]; st.char=[]; st.deck=newDeck(); st.phase='deal'; st.peek=false; st.peekWin=false; st.lastDraw=null; st.userDone=false; st.charDone=false; waitingUndo=false; clearUndoChoice(); await chooseBlackjackOrder(); st.phase='deal'; setStatus((st.tieBreak?'决胜局｜':'') + (st.firstMover==='user'?'你先手':charName+'先手') + '｜发牌中'); draw(); const seq=st.firstMover==='user'?['user','char','user','char']:['char','user','char','user']; for(const who of seq){ await delay(120); drawCard(who); draw(); } await delay(250); const u=handValue(st.user), c=handValue(st.char); if(u.bj||c.bj){ st.phase='settle'; draw(); if(u.bj&&c.bj) await settleRound('tie','双方 Blackjack｜平局',40,40,true); else if(u.bj){ st.details.blackjacks++; env.speak('blackjack','player_blackjack'); await settleRound('user','Blackjack！',150,0,true); } else { env.speak('blackjack','char_blackjack'); await settleRound('char','Char Blackjack',0,150,true); } return; } if(st.firstMover==='char'){ busy=false; await charTurn(); } else { st.phase='player'; busy=false; setStatus('你的回合'); draw(); } }
    async function playerHit(){ if(st.phase!=='player'||busy) return; if(handValue(st.user).total>=19) env.speak('blackjack','risky_hit'); busy=true; const before=st.user.slice(); const c=drawCard('user'); st.lastDraw={card:c,before}; draw(); await delay(220); const v=handValue(st.user); if(st.protectReady){ st.protectReady=false; st.details.protectUsed++; st.tools.protect=Math.max(0,st.tools.protect||0); if(v.bust){ st.user=before; st.lastDraw=null; env.speak('blackjack','protect'); toastMid('护牌生效'); busy=false; draw(); return; } }
      if(st.user.length>=6&&!v.bust) st.details.sixCard=true;
      if(v.exact21){ st.details.exact21++; env.speak('blackjack','player_21'); toastMid('21！'); draw(); await delay(500); busy=false; playerStand(); return; }
      if(v.bust){ st.details.busts++; st.details.consecutiveBusts++; if(st.peekWin) st.details.peekBust=true; if(st.details.consecutiveBusts>=3) st.details.tripleBust=true; env.speak('blackjack','player_bust'); draw(); if((st.tools.undo||0)>0){ showUndoChoice(); return; } await delay(700); await settleRound('char','玩家爆牌',0,100,false); return; }
      busy=false; draw(); }
    function showUndoChoice(){ clearUndoChoice(); waitingUndo=true; busy=true; const div=env.getHostDocument().createElement('div'); div.className='wb-bj-choice'; div.id='bj-undo-choice'; div.innerHTML='<span>使用反悔？</span><button class="primary" id="bj-use-undo">反悔</button><button id="bj-accept-bust">接受结果</button>'; env.qs('.wb-bj-table',box).appendChild(div); env.qs('#bj-use-undo').onclick=useUndo; env.qs('#bj-accept-bust').onclick=()=>acceptBust(); undoTimer=setTimeout(()=>{ if(env.qs('#bj-undo-choice')) acceptBust(); },3000); draw(); }
    function clearUndoChoice(){ if(undoTimer) clearTimeout(undoTimer); undoTimer=null; waitingUndo=false; const old=env.qs('#bj-undo-choice',box); if(old) old.remove(); }
    async function acceptBust(){ if(!waitingUndo) return; clearUndoChoice(); busy=true; await settleRound('char','玩家爆牌',0,100,false); }
    function useUndo(){ if(!st.lastDraw||!(st.tools.undo>0)) return; clearUndoChoice(); st.user=st.lastDraw.before.slice(); st.lastDraw=null; st.tools.undo--; st.details.undoUsed++; st.details.busts=Math.max(0,(st.details.busts||0)-1); st.details.consecutiveBusts=0; env.speak('blackjack','undo'); toastMid('已反悔'); busy=false; draw(); }
    async function playerStand(){ if(st.phase!=='player'||busy) return; busy=true; st.userDone=true; st.lastDraw=null; clearUndoChoice(); draw(); save(true); if(st.charDone) await compareRound(); else await charTurn(); }
    function remainingCounts(){ const m={}; st.deck.forEach(c=>{ const v=c.r==='A'?'A':(/[JQK]/.test(c.r)?'10':c.r); m[v]=(m[v]||0)+1; }); return m; }
    function bustProb(hand){ const m=remainingCounts(), total=Object.values(m).reduce((a,b)=>a+b,0)||1; let bad=0; Object.entries(m).forEach(([r,n])=>{ const c={r:r==='10'?'10':r,s:'♠'}; if(handValue(hand.concat([c])).bust) bad+=n; }); return bad/total; }
    function standValue(c,p){ if(c>21) return 0; if(c>p) return 1; if(c===p) return .35; return 0; }
    function hitValue(hand,p,depth){ const m=remainingCounts(), total=Object.values(m).reduce((a,b)=>a+b,0)||1; let ev=0; Object.entries(m).forEach(([r,n])=>{ const c={r:r==='10'?'10':r,s:'♠'}, h=hand.concat([c]), v=handValue(h).total; if(v>21) ev+=0; else if(depth<=0||v>=21) ev+=standValue(v,p)*n/total; else ev+=Math.max(standValue(v,p), hitValue(h,p,depth-1))*n/total; }); return ev; }
    function decideChar(){ const c=handValue(st.char), p=handValue(st.user).total; if(c.total<=11) return 'hit'; if(c.total>=21) return 'stand'; let hit=.5, stand=.5; if(st.level<=2){ if(c.total<=14) hit=.85; else if(c.total===15) hit=.70; else if(c.total===16) hit=p<=15?.35:.75; else if(c.total===17) hit=.10; else hit=.03; return Math.random()<hit?'hit':'stand'; }
      if(st.level<=5){ if(c.total>p) hit=.12; else if(c.total===p) hit=c.total<18?.45:.12; else hit=c.total<=16?.85:.62; }
      else { stand=standValue(c.total,p); hit=hitValue(st.char,p,st.level>=7?6:1); }
      const mood=st.level>=8?personality():st.personality; if(mood==='谨慎') hit-=.06; if(mood==='冒险'&&c.total<p) hit+=.08; const best=hit>stand?'hit':'stand', other=best==='hit'?'stand':'hit', gap=Math.abs(hit-stand); const err=ERR[levelIndex()]; if(gap<.18&&Math.random()<err) return other; return best; }
    async function charTurn(){ st.phase='char'; busy=true; draw(); await delay(300); while(!over){ const v=handValue(st.char); if(v.bust){ st.details.charBusts++; st.details.charConsecutiveBusts++; if(st.details.charConsecutiveBusts>=3) st.details.charTripleBust=true; env.speak('blackjack','char_bust'); await settleRound('user','Char爆牌',100,0,false); return; } if(v.exact21&&st.char.length>=3) env.speak('blackjack','char_21'); setStatus(charName+'正在思考……'); await delay(450+Math.random()*400); const act=decideChar(); if(act==='hit'){ setStatus(charName+'：要牌'); await delay(300); drawCard('char'); draw(); continue; } setStatus(charName+'：停牌'); st.charDone=true; await delay(400); if(st.userDone) await compareRound(); else { st.phase='player'; busy=false; setStatus('你的回合'); draw(); save(true); } return; } }
    async function compareRound(){ const u=handValue(st.user), c=handValue(st.char); if(u.bust) return settleRound('char','玩家爆牌',0,100,false); if(c.bust) return settleRound('user','Char爆牌',100,0,false); if(u.total>c.total) return settleRound('user','你赢了',winPoints(st.user),0,false); if(c.total>u.total) return settleRound('char','Char赢了',0,winPoints(st.char),false); return settleRound('tie','平局',40,40,false); }
    function winPoints(h){ const v=handValue(h); return v.bj?150:(h.length>=3&&v.total===21?120:100); }
    function streakBonus(who){ const n=who==='user'?st.userStreak:st.charStreak; return n>=6?100:Math.max(0,(n-1)*20); }
    async function settleRound(winner,msg,uPts,cPts,bj){ st.phase='settle'; st.lastWinner=winner; const uv=handValue(st.user), cv=handValue(st.char); if(!uv.bust) st.details.consecutiveBusts=0; if(!cv.bust) st.details.charConsecutiveBusts=0; draw(); if(winner==='user'){ st.userStreak++; st.charStreak=0; st.details.wins++; if(st.tieBreak) st.details.wonTiebreak=true; if(st.peekWin) st.details.peekWin=true; if(st.user.length>=6&&!uv.bust) st.details.sixCard=true; if(st.userStreak===5){ env.speak('blackjack','win5'); } } else if(winner==='char'){ st.charStreak++; st.userStreak=0; st.details.losses++; if(st.char.length>=6&&!cv.bust) st.details.charSixCard=true; } else { st.details.ties++; }
      if(winner==='user') uPts+=streakBonus('user'); if(winner==='char') cPts+=streakBonus('char'); st.userScore+=uPts; st.charScore+=cPts; st.total+=uPts; env.setScore('blackjack',st.total); st.maxStreak=Math.max(st.maxStreak,st.userStreak); st.details.maxStreak=st.maxStreak; if(winner==='user') env.speak('blackjack','player_win'); if(winner==='char') env.speak('blackjack','char_win'); if(Math.abs(st.userScore-st.charScore)<=50) env.speak('blackjack','close_score'); toastMid(msg+(uPts?(' +'+uPts):'')); if(uPts) gain('user','+'+uPts+(bj?' BLACKJACK':'')); if(cPts) gain('char','+'+cPts); draw(); save(true); await delay(1300); await checkLevelEnd(winner); }
    async function checkLevelEnd(lastWinner){ const target=st.target, u=st.userScore>=target, c=st.charScore>=target; if(u||c){ if(u&&c&&st.userScore===st.charScore){ st.tieBreak=true; toastMid('决胜局'); await delay(900); startRound(); return; } const userWin=u&&(!c||st.userScore>st.charScore); if(userWin){ if(st.level>=8){ st.details.completedAll=true; await delay(600); finishAll(); return; } toastMid('第'+st.level+'关胜利'); await delay(1500); nextLevel(); } else fail(); return; } await delay(900); startRound(); }
    function blackjackBestScore(){ const cur=env.scores().blackjack; return (cur && typeof cur === 'object') ? Number(cur.user || 0) : Number(cur || 0); }
    function showBlackjackRevive(onRevive,onSettle){
      if((st.reviveLeft||0)<=0){ onSettle(); return; }
      busy=true;
      const doc=env.getHostDocument(); const old=env.qs('#wb-revive-mask', doc); if(old) old.remove();
      const mask=doc.createElement('div'); mask.className=env.modalMaskClass(); mask.id='wb-revive-mask';
      mask.innerHTML='<div class="wb-modal"><div class="wb-modal-title">看广告免费复活</div><div style="margin-bottom:10px;line-height:1.8;">骗你的，不看广告也能复活</div><div class="wb-api-status" style="margin-bottom:12px;">剩余复活次数：'+env.esc(st.reviveLeft)+'</div><div class="wb-actions"><button class="wb-btn primary" id="wb-revive-ok">确认复活</button><button class="wb-btn" id="wb-revive-giveup">认输结算</button></div></div>';
      env.appendModalMask(mask);
      env.qs('#wb-revive-ok', mask).onclick=()=>{ mask.remove(); st.reviveLeft=Math.max(0,(st.reviveLeft||0)-1); st.details.reviveUsed=(st.details.reviveUsed||0)+1; onRevive(); };
      env.qs('#wb-revive-giveup', mask).onclick=()=>{ mask.remove(); onSettle(); };
    }
    function settleFail(){ over=true; env.clearProgress('blackjack'); env.setScore('blackjack',Math.max(blackjackBestScore(),st.total)); st.details.score=st.total; st.details.level=st.level; env.showGameOver('blackjack','本次挑战结束','到达第'+st.level+'关，累计总分：'+st.total+'分，最高连胜：'+st.maxStreak,{outcome:'ta_win'},{details:Object.assign({},st.details, { reviveLeft:st.reviveLeft||0 })}); }
    function fail(){ showBlackjackRevive(()=>{ busy=false; st.userScore=0; st.charScore=0; st.userStreak=0; st.charStreak=0; st.tieBreak=false; st.tools={hint:2,peek:1,undo:1,protect:st.level>=3?1:0}; st.protectReady=false; toastMid('复活成功，重开第'+st.level+'关'); save(true); startRound(); }, settleFail); }
    function finishAll(){ over=true; env.clearProgress('blackjack'); env.setScore('blackjack',Math.max(blackjackBestScore(),st.total)); st.details.completedAll=true; st.details.score=st.total; st.details.level=8; env.showGameOver('blackjack','你赢过Char了！','累计总分：'+st.total+'分，胜局：'+st.details.wins+'，负局：'+st.details.losses+'，平局：'+st.details.ties+'，Blackjack：'+st.details.blackjacks+'，爆牌：'+st.details.busts+'，最高连胜：'+st.maxStreak,{outcome:'user_win'},{details:Object.assign({},st.details)}); }
    function useTool(t){ if(busy||over||!st.tools||st.tools[t]<=0) return; if(t!=='undo'&&st.phase!=='player') return; if(t==='hint'){ st.tools.hint--; st.details.hintUsed++; const p=bustProb(st.user); env.speak('blackjack','hint'); setStatus('建议：'+(p>.42?'停牌':'要牌')+'｜爆牌概率约'+Math.round(p*100)+'%'); setTimeout(()=>{ if(env.currentGame==='blackjack') setStatus(st.phase==='player'?'你的回合':''); },2500); }
      if(t==='peek'&&st.phase==='player'){ busy=true; st.tools.peek--; st.details.peekUsed++; st.peek=true; st.peekWin=true; env.speak('blackjack','peek'); draw(); setTimeout(()=>{ st.peek=false; busy=false; draw(); },2000); }
      if(t==='undo') useUndo(); if(t==='protect'&&st.phase==='player'){ st.tools.protect--; st.protectReady=true; toastMid('护牌已准备'); draw(); } draw(); }
    if(state && (st.user.length || st.char.length || st.round || st.total || st.userScore || st.charScore)){
      if(!st.user.length || !st.char.length){ startRound(); return; }
      if(st.phase==='deal' || st.phase==='order') st.phase=st.firstMover==='char'&&!st.charDone?'char':'player';
      draw();
      if(st.phase==='char') setTimeout(()=>{ if(env.currentGame==='blackjack'&&!over) charTurn(); },180);
      else if(st.phase==='settle') setTimeout(()=>{ if(env.currentGame==='blackjack'&&!over) checkLevelEnd(st.lastWinner || ''); },300);
      else { st.phase='player'; busy=false; setStatus('你的回合'); draw(); }
    } else startLevel();
  }
  startBlackjack(state);
  return env.activeGameController || null;
}
