// Game-owned plain text: included in the same immutable package as Sudoku.
// Placeholders are one-based display values supplied by the UI, never HTML.
const en = {
  title:'Sudoku', subtitle:'A moment of focus',
  difficulty:{easy:'Easy',medium:'Medium',hard:'Hard',expert:'Expert'},
  time:'Time',filled:'Filled',remaining:'Remaining',notes:'Notes',notesOn:'Notes on',notesOff:'Notes off',
  undo:'Undo',redo:'Redo',erase:'Erase',hint:'Hint',pause:'Pause',resume:'Continue',saveExit:'Save & exit',
  help:'How to play',settings:'Options',close:'Close',back:'Back',applyHint:'Apply hint',revealHint:'Reveal this answer',
  autoNotes:'Fill notes',autoNotesTitle:'Replace your notes?',
  autoNotesBody:'Fill every empty cell with candidates allowed by the current entries, including any mistakes. This replaces your notes and can be undone.',
  confirm:'Confirm',cancel:'Cancel',autoClean:'Remove matching notes',
  autoCleanDetail:'After entering a number, remove that note from its row, column and box. Undo restores the notes too.',
  numberFirst:'Number first',numberFirstDetail:'Choose a number, then tap cells to enter it. Turn this off to choose a cell first.',
  autoCheck:'Check against solution',autoCheckDetail:'Mark entries that differ from the saved solution. Repeated numbers are always marked as conflicts.',
  selectedCell:'Row {row}, column {col}',fixedCell:'Given',emptyCell:'Empty',noteList:'Notes: {digits}',countRemaining:'{count} left',
  selectCell:'Choose a cell',selectNumber:'Choose a number',penMode:'Number mode',noteMode:'Notes mode',
  pausedTitle:'Take a break',pausedBody:'The board and timer are paused. Continue when you are ready.',
  helpTitle:'Make room for every number',
  helpBody:'Use 1–9 once in each row, column and 3×3 box. Choose a cell then a number, or enable Number first. Notes let you toggle candidates without entering an answer. Undo and redo also restore notes. Hints explain a step before you apply it; revealing an answer is labelled separately. New puzzles are checked for a unique solution. Keyboard: arrows to move, 1–9 to enter, Delete to erase, N for notes, H for a hint, Ctrl/⌘+Z to undo, Ctrl/⌘+Y or Ctrl/⌘+Shift+Z to redo, Escape to pause.',
  hintTitle:'One step at a time',hintCount:'Hints used: {hints}. Viewing an answer counts once; reopening this explanation does not count again.',
  hintConflict:'Check row {row}, column {col}: this entry repeats a number in its row, column or box. Correct a conflicting entry first.',
  hintContradiction:'The current entries cannot complete this puzzle. Review or undo recent entries before continuing.',
  hintNaked:'Row {row}, column {col} has only one candidate: {digit}. Every other number is excluded by its row, column or box.',
  hintHidden:'In {unit} {unitIndex}, only row {row}, column {col} can hold {digit}. Other empty cells in that unit exclude it.',
  hintReveal:'No supported single-step explanation was found. You can reveal {digit} at row {row}, column {col}; this is answer assistance, not a demonstrated logical step.',
  hintComplete:'Every cell is filled correctly.',hintUnavailable:'No hint is available within the current search limit. Your entries have not changed.',
  row:'row',column:'column',box:'box',completeTitle:'Sudoku complete',completeBody:'Score: {score} · Hints used: {hints}',
  noUndo:'Nothing to undo',noRedo:'Nothing to redo',uniquePuzzle:'Unique solution',loading:'Preparing puzzle…',
  legacyNotice:'Your previous game is preserved. When a unique solution cannot be confirmed, only row, column and box conflicts are marked.',
};
const labels = {
  en,
  'zh-CN':{
    title:'数独',subtitle:'专注片刻',difficulty:{easy:'简单',medium:'中等',hard:'困难',expert:'专家'},
    time:'用时',filled:'已填',remaining:'剩余',notes:'笔记',notesOn:'笔记已开',notesOff:'笔记已关',
    undo:'撤销',redo:'重做',erase:'擦除',hint:'提示',pause:'暂停',resume:'继续',saveExit:'保存并退出',
    help:'玩法',settings:'选项',close:'关闭',back:'返回',applyHint:'应用提示',revealHint:'揭示此格答案',
    autoNotes:'填入候选',autoNotesTitle:'替换当前笔记？',
    autoNotesBody:'根据当前已填数字，为所有空格填入候选数；错误填数也会影响候选。这会替换现有笔记，可以撤销。',
    confirm:'确定',cancel:'取消',autoClean:'自动清理同数笔记',
    autoCleanDetail:'填入数字后，移除同行、同列、同宫中的同数笔记；撤销时一并恢复。',
    numberFirst:'先选数字',numberFirstDetail:'先选一个数字，再点格子连续填入；关闭后先选格子再填数。',
    autoCheck:'对照答案检查',autoCheckDetail:'标记与已保存答案不同的填数；同行、同列、同宫的重复数字始终标记为冲突。',
    selectedCell:'第{row}行，第{col}列',fixedCell:'题面数字',emptyCell:'空格',noteList:'笔记：{digits}',countRemaining:'剩{count}个',
    selectCell:'请选择格子',selectNumber:'请选择数字',penMode:'填数模式',noteMode:'笔记模式',
    pausedTitle:'稍作休息',pausedBody:'棋盘和计时已暂停，准备好后继续。',
    helpTitle:'让每个数字各就其位',
    helpBody:'每行、每列和每个3×3宫都应包含1—9，且不重复。先选格子再选数字，也可开启“先选数字”。笔记用于增删候选数，不会填入答案；撤销和重做会同时恢复笔记。提示先解释，再由你确认应用；直接揭示答案会单独说明。新题经过唯一解校验。键盘：方向键移动，1—9填数，Delete擦除，N切换笔记，H提示，Ctrl/⌘+Z撤销，Ctrl/⌘+Y或Ctrl/⌘+Shift+Z重做，Escape暂停。',
    hintTitle:'一步一步解开',hintCount:'已用提示：{hints}次。查看含答案的说明计为一次提示，重复查看本条说明不重复计次。',
    hintConflict:'检查第{row}行、第{col}列：此格与同行、同列或同宫的数字重复。请先修正冲突填数。',
    hintContradiction:'当前填数无法完成这道题，请检查或撤销最近的填数。',
    hintNaked:'第{row}行、第{col}列只剩一个候选数：{digit}。其他数字已被同行、同列或同宫排除。',
    hintHidden:'在第{unitIndex}{unit}中，只有第{row}行、第{col}列能填{digit}；该区域其他空格均排除了它。',
    hintReveal:'尚未找到支持的单步逻辑说明。你可以揭示第{row}行、第{col}列的答案{digit}；这是答案辅助，不代表已给出逻辑推导。',
    hintComplete:'所有格子均已正确填完。',hintUnavailable:'本次搜索范围内暂未找到提示，当前填数没有改变。',
    row:'行',column:'列',box:'宫',completeTitle:'数独完成',completeBody:'本局得分：{score} · 使用提示：{hints}次',
    noUndo:'没有可撤销的操作',noRedo:'没有可重做的操作',uniquePuzzle:'唯一解',loading:'正在准备题目…',
    legacyNotice:'已保留旧局。无法确认唯一解时，仅标记行、列和宫内的重复冲突。',
  },
  'zh-TW':{
    title:'數獨',subtitle:'專注片刻',difficulty:{easy:'簡單',medium:'中等',hard:'困難',expert:'專家'},
    time:'用時',filled:'已填',remaining:'剩餘',notes:'筆記',notesOn:'筆記已開',notesOff:'筆記已關',
    undo:'復原',redo:'重做',erase:'擦除',hint:'提示',pause:'暫停',resume:'繼續',saveExit:'儲存並退出',
    help:'玩法',settings:'選項',close:'關閉',back:'返回',applyHint:'套用提示',revealHint:'揭示此格答案',
    autoNotes:'填入候選',autoNotesTitle:'取代目前筆記？',
    autoNotesBody:'依目前已填數字，為所有空格填入候選數；錯誤填數也會影響候選。這會取代現有筆記，可以復原。',
    confirm:'確定',cancel:'取消',autoClean:'自動清理同數筆記',
    autoCleanDetail:'填入數字後，移除同列、同行、同宮中的同數筆記；復原時一併還原。',
    numberFirst:'先選數字',numberFirstDetail:'先選一個數字，再點格子連續填入；關閉後先選格子再填數。',
    autoCheck:'對照答案檢查',autoCheckDetail:'標記與已儲存答案不同的填數；同行、同列、同宮的重複數字一律標記為衝突。',
    selectedCell:'第{row}橫列，第{col}直行',fixedCell:'題面數字',emptyCell:'空格',noteList:'筆記：{digits}',countRemaining:'剩{count}個',
    selectCell:'請選擇格子',selectNumber:'請選擇數字',penMode:'填數模式',noteMode:'筆記模式',
    pausedTitle:'稍作休息',pausedBody:'棋盤與計時已暫停，準備好後繼續。',
    helpTitle:'讓每個數字各就其位',
    helpBody:'每條橫列、直行及每個3×3宮都應包含1—9，且不重複。先選格子再選數字，也可開啟「先選數字」。筆記可增刪候選數，不會填入答案；復原和重做會同時還原筆記。提示先解釋，再由你確認套用；直接揭示答案會另外說明。新題經過唯一解驗證。鍵盤：方向鍵移動，1—9填數，Delete擦除，N切換筆記，H提示，Ctrl/⌘+Z復原，Ctrl/⌘+Y或Ctrl/⌘+Shift+Z重做，Escape暫停。',
    hintTitle:'一步一步解開',hintCount:'已用提示：{hints}次。查看含答案的說明計為一次提示，重複查看本條說明不重複計次。',
    hintConflict:'檢查第{row}橫列、第{col}直行：此格與同列、同行或同宮的數字重複。請先修正衝突填數。',
    hintContradiction:'目前填數無法完成這道題，請檢查或復原最近的填數。',
    hintNaked:'第{row}橫列、第{col}直行只剩一個候選數：{digit}。其他數字已被同列、同行或同宮排除。',
    hintHidden:'在第{unitIndex}{unit}中，只有第{row}橫列、第{col}直行能填{digit}；該區域其他空格均已排除它。',
    hintReveal:'尚未找到支援的單步邏輯說明。你可以揭示第{row}橫列、第{col}直行的答案{digit}；這是答案輔助，不代表已提供邏輯推導。',
    hintComplete:'所有格子均已正確填完。',hintUnavailable:'本次搜尋範圍內暫未找到提示，目前填數沒有改變。',
    row:'橫列',column:'直行',box:'宮',completeTitle:'數獨完成',completeBody:'本局得分：{score} · 使用提示：{hints}次',
    noUndo:'沒有可復原的操作',noRedo:'沒有可重做的操作',uniquePuzzle:'唯一解',loading:'正在準備題目…',
    legacyNotice:'已保留舊局。無法確認唯一解時，只標記橫列、直行及宮內的重複衝突。',
  },
  ja:{
    title:'ナンプレ',subtitle:'集中するひととき',difficulty:{easy:'初級',medium:'中級',hard:'上級',expert:'達人'},
    time:'時間',filled:'入力済み',remaining:'残り',notes:'メモ',notesOn:'メモ ON',notesOff:'メモ OFF',
    undo:'元に戻す',redo:'やり直す',erase:'消す',hint:'ヒント',pause:'一時停止',resume:'続ける',saveExit:'保存して終了',
    help:'遊び方',settings:'設定',close:'閉じる',back:'戻る',applyHint:'ヒントを適用',revealHint:'このマスの答えを見る',
    autoNotes:'候補を記入',autoNotesTitle:'メモを置き換えますか？',
    autoNotesBody:'現在の入力から候補を計算し、すべての空きマスに記入します。誤った入力も候補に影響します。今のメモは置き換わりますが、元に戻せます。',
    confirm:'決定',cancel:'キャンセル',autoClean:'同じ数字のメモを消す',
    autoCleanDetail:'数字を入力すると、同じ行・列・ブロックの該当メモを消します。「元に戻す」でメモも復元します。',
    numberFirst:'数字を先に選ぶ',numberFirstDetail:'数字を選んでからマスをタップして入力します。OFFにするとマスを先に選びます。',
    autoCheck:'答えと照合する',autoCheckDetail:'保存された正解と違う入力を示します。行・列・ブロックの数字の重複は常に表示します。',
    selectedCell:'{row}行目、{col}列目',fixedCell:'最初からある数字',emptyCell:'空きマス',noteList:'メモ：{digits}',countRemaining:'残り{count}個',
    selectCell:'マスを選んでください',selectNumber:'数字を選んでください',penMode:'数字入力',noteMode:'メモ入力',
    pausedTitle:'ひと休み',pausedBody:'盤面とタイマーは停止中です。準備ができたら続けましょう。',
    helpTitle:'数字を一つずつ整理しよう',
    helpBody:'各行・列・3×3ブロックに1～9を一度ずつ入れます。マスを先に選ぶか、「数字を先に選ぶ」を使います。メモは答えを入れずに候補を追加・削除できます。「元に戻す」「やり直す」はメモも復元します。ヒントは説明を読んでから適用し、答えの表示とは区別されます。新しい問題は解が一つであることを確認します。キーボード：矢印で移動、1～9で入力、Deleteで消去、Nでメモ、Hでヒント、Ctrl/⌘+Zで元に戻す、Ctrl/⌘+YまたはCtrl/⌘+Shift+Zでやり直す、Escapeで一時停止。',
    hintTitle:'一歩ずつ解こう',hintCount:'使用ヒント：{hints}回。答えを含む説明の表示は1回と数えます。同じ説明を開き直しても増えません。',
    hintConflict:'{row}行目、{col}列目を確認してください。同じ行・列・ブロックに同じ数字があります。まず重複する入力を修正しましょう。',
    hintContradiction:'現在の入力のままでは完成できません。最近の入力を確認するか、元に戻してください。',
    hintNaked:'{row}行目、{col}列目の候補は{digit}だけです。他の数字は同じ行・列・ブロックによって除外されます。',
    hintHidden:'{unitIndex}番目の{unit}では、{digit}を入れられるのは{row}行目、{col}列目だけです。他の空きマスには入りません。',
    hintReveal:'対応する一手の論理的な説明が見つかりませんでした。{row}行目、{col}列目の答え{digit}を表示できます。これは答えの補助であり、論理的な説明ではありません。',
    hintComplete:'すべてのマスに正しい数字が入りました。',hintUnavailable:'今回の探索範囲ではヒントが見つかりませんでした。入力は変わっていません。',
    row:'行',column:'列',box:'ブロック',completeTitle:'ナンプレ完成',completeBody:'スコア：{score} · ヒント使用：{hints}回',
    noUndo:'元に戻す操作はありません',noRedo:'やり直す操作はありません',uniquePuzzle:'解は一つ',loading:'問題を準備中…',
    legacyNotice:'前のゲームを維持しています。解が一つと確認できない場合は、行・列・ブロックの重複だけを表示します。',
  },
  ko:{
    title:'스도쿠',subtitle:'집중하는 시간',difficulty:{easy:'쉬움',medium:'보통',hard:'어려움',expert:'전문가'},
    time:'시간',filled:'입력 완료',remaining:'남은 칸',notes:'메모',notesOn:'메모 켜짐',notesOff:'메모 꺼짐',
    undo:'실행 취소',redo:'다시 실행',erase:'지우기',hint:'힌트',pause:'일시 정지',resume:'계속하기',saveExit:'저장 후 나가기',
    help:'게임 방법',settings:'설정',close:'닫기',back:'돌아가기',applyHint:'힌트 적용',revealHint:'이 칸의 정답 보기',
    autoNotes:'후보 채우기',autoNotesTitle:'현재 메모를 바꿀까요?',
    autoNotesBody:'현재 입력을 기준으로 모든 빈칸에 후보를 채웁니다. 잘못된 입력도 후보에 영향을 줍니다. 기존 메모를 대체하며 실행 취소할 수 있습니다.',
    confirm:'확인',cancel:'취소',autoClean:'같은 숫자 메모 지우기',
    autoCleanDetail:'숫자를 입력하면 같은 행·열·구역의 해당 메모를 지웁니다. 실행 취소하면 메모도 복원됩니다.',
    numberFirst:'숫자 먼저 선택',numberFirstDetail:'숫자를 고른 뒤 칸을 눌러 연속 입력합니다. 끄면 칸을 먼저 고릅니다.',
    autoCheck:'정답과 비교',autoCheckDetail:'저장된 정답과 다른 입력을 표시합니다. 같은 행·열·구역의 중복 숫자는 항상 표시합니다.',
    selectedCell:'{row}행, {col}열',fixedCell:'주어진 숫자',emptyCell:'빈칸',noteList:'메모: {digits}',countRemaining:'{count}개 남음',
    selectCell:'칸을 선택하세요',selectNumber:'숫자를 선택하세요',penMode:'숫자 입력',noteMode:'메모 입력',
    pausedTitle:'잠깐 쉬어 가요',pausedBody:'보드와 타이머가 멈췄습니다. 준비되면 계속하세요.',
    helpTitle:'숫자를 하나씩 채워 보세요',
    helpBody:'각 행·열·3×3 구역에 1~9를 한 번씩 넣으세요. 칸을 먼저 고르거나 숫자 먼저 선택을 켤 수 있습니다. 메모는 정답을 입력하지 않고 후보를 추가·삭제합니다. 실행 취소와 다시 실행은 메모도 복원합니다. 힌트는 설명을 읽고 적용하며, 정답 공개는 따로 안내합니다. 새 문제는 정답이 하나인지 확인합니다. 키보드: 방향키 이동, 1~9 입력, Delete 지우기, N 메모, H 힌트, Ctrl/⌘+Z 실행 취소, Ctrl/⌘+Y 또는 Ctrl/⌘+Shift+Z 다시 실행, Escape 일시 정지.',
    hintTitle:'한 단계씩 풀어 봐요',hintCount:'사용한 힌트: {hints}회. 정답이 있는 설명을 보면 1회로 계산합니다. 같은 설명을 다시 열어도 늘지 않습니다.',
    hintConflict:'{row}행 {col}열을 확인하세요. 같은 행·열·구역에 같은 숫자가 있습니다. 중복된 입력부터 수정하세요.',
    hintContradiction:'현재 입력으로는 문제를 완성할 수 없습니다. 최근 입력을 확인하거나 실행 취소하세요.',
    hintNaked:'{row}행 {col}열에는 후보가 {digit} 하나뿐입니다. 다른 숫자는 같은 행·열·구역 때문에 제외됩니다.',
    hintHidden:'{unitIndex}번째 {unit}에서 {digit}을 넣을 수 있는 곳은 {row}행 {col}열뿐입니다. 그 구역의 다른 빈칸에는 넣을 수 없습니다.',
    hintReveal:'지원하는 한 단계 논리 설명을 찾지 못했습니다. {row}행 {col}열의 정답 {digit}을 공개할 수 있습니다. 이는 정답 도움이며 논리적 풀이 설명은 아닙니다.',
    hintComplete:'모든 칸을 올바르게 채웠습니다.',hintUnavailable:'이번 탐색 범위에서 힌트를 찾지 못했습니다. 입력은 바뀌지 않았습니다.',
    row:'행',column:'열',box:'구역',completeTitle:'스도쿠 완성',completeBody:'점수: {score} · 힌트 사용: {hints}회',
    noUndo:'취소할 동작이 없습니다',noRedo:'다시 실행할 동작이 없습니다',uniquePuzzle:'정답은 하나',loading:'문제 준비 중…',
    legacyNotice:'이전 게임을 유지했습니다. 정답이 하나인지 확인할 수 없으면 행·열·구역의 중복만 표시합니다.',
  },
};

export function sudokuLabels(locale) {
  const localized = Object.hasOwn(labels, locale) ? labels[locale] : en;
  return {...en, ...localized, difficulty:{...en.difficulty, ...localized.difficulty}};
}

// Pure interpolation only; callers use textContent or their usual HTML escape.
export function formatSudokuLabel(template, values = {}) {
  return String(template).replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g, (token, key) =>
    Object.hasOwn(values, key) ? String(values[key]) : token);
}
