// Quiet, high-contrast game-owned UI; numerals never use raster art.
export const sudokuStyles=`
#wb-sudoku-fullscreen{--sd-paper:#fafaf7;--sd-surface:#fff;--sd-ink:#213d44;--sd-muted:#5e7278;--sd-line:#cdd8d9;--sd-heavy:#516b72;--sd-accent:#126e71;--sd-wash:#ecf3f2;--sd-peer:#edf4f4;--sd-same:#cce7e4;--sd-selected:#d4edec;--sd-error:#b23241;--sd-error-bg:#fce8eb;position:fixed;inset:0;z-index:2147483000;background:var(--sd-paper);color:var(--sd-ink);font-family:system-ui,-apple-system,sans-serif;display:grid;grid-template-rows:auto minmax(0,1fr);padding:env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);box-sizing:border-box;isolation:isolate;overflow:hidden;overscroll-behavior:none;-webkit-user-select:none;user-select:none}
#wb-sudoku-fullscreen[data-theme=night],#wb-sudoku-fullscreen[data-theme=cyber],#wb-sudoku-fullscreen[data-theme=card]{--sd-paper:#132328;--sd-surface:#1c3037;--sd-ink:#e1eeee;--sd-muted:#aec2c8;--sd-line:#3e5961;--sd-heavy:#94b0b7;--sd-accent:#8cdbd2;--sd-wash:#213a42;--sd-peer:#28444d;--sd-same:#365e67;--sd-selected:#326067;--sd-error:#ffb1be;--sd-error-bg:#582e3b}
#wb-sudoku-fullscreen[data-theme=mono]{--sd-ink:#151515;--sd-accent:#121212;--sd-heavy:#111;--sd-selected:#ddd;--sd-same:#e8e8e8;--sd-peer:#f1f1f1}
#wb-sudoku-fullscreen *{box-sizing:border-box}#wb-sudoku-fullscreen button{font:inherit;cursor:pointer;touch-action:manipulation;-webkit-tap-highlight-color:transparent;color:inherit}#wb-sudoku-fullscreen button:focus-visible,#wb-sudoku-fullscreen input:focus-visible{outline:3px solid var(--sd-accent);outline-offset:2px}#wb-sudoku-fullscreen [hidden]{display:none!important}
#wb-sudoku-fullscreen .sd-head{display:grid;grid-template-columns:48px 1fr 48px;align-items:center;padding:10px 16px;gap:12px;border-bottom:1px solid var(--sd-line);background:var(--sd-surface)}
#wb-sudoku-fullscreen .sd-heading{text-align:center}.sd-heading h1{font-size:22px;line-height:1.2;letter-spacing:2px;margin:0;font-weight:750}.sd-heading small{display:block;color:var(--sd-muted);font-size:10px;letter-spacing:1px;margin-top:3px}
#wb-sudoku-fullscreen .sd-round{width:44px;height:44px;border:0;background:var(--sd-wash);border-radius:14px;font-size:25px;display:grid;place-items:center}.sd-round .sd-label{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}
#wb-sudoku-fullscreen .sd-layout{width:100%;max-width:590px;justify-self:center;min-height:0;min-width:0;padding:12px 14px 16px;display:grid;grid-template-rows:minmax(0,1fr) auto;gap:13px}.sd-board-area{min-height:0;min-width:0;display:grid;grid-template-rows:auto minmax(0,1fr) 3px;gap:10px}.sd-meta{display:flex;align-items:center;justify-content:space-between;color:var(--sd-muted);font-size:13px;padding:0 3px}.sd-difficulty{font-weight:650;color:var(--sd-accent);background:var(--sd-wash);border-radius:7px;padding:4px 10px}.sd-clock{font-variant-numeric:tabular-nums;font-weight:600;letter-spacing:1px}.sd-board-wrap{min-height:0;min-width:0;display:grid;place-items:center}
#wb-sudoku-fullscreen .sd-grid{width:100%;aspect-ratio:1;flex:none;display:grid;grid-template-columns:repeat(9,minmax(0,1fr));grid-template-rows:repeat(9,minmax(0,1fr));background:var(--sd-surface);border:2px solid var(--sd-heavy);border-radius:4px;overflow:hidden;box-shadow:0 5px 14px #172e3610;touch-action:manipulation}
#wb-sudoku-fullscreen .sd-cell{position:relative;min-width:0;min-height:0;border:0;border-right:1px solid var(--sd-line);border-bottom:1px solid var(--sd-line);border-radius:0;margin:0;padding:0;background:var(--sd-surface);color:var(--sd-accent);display:grid;place-items:center;line-height:1;font-variant-numeric:tabular-nums;font-size:var(--sd-cell-font,23px);font-weight:650;box-shadow:none}
#wb-sudoku-fullscreen .sd-cell:nth-child(9n){border-right:0}#wb-sudoku-fullscreen .sd-cell:nth-child(n+73){border-bottom:0}#wb-sudoku-fullscreen .sd-cell.sd-box-right{border-right:2px solid var(--sd-heavy)}#wb-sudoku-fullscreen .sd-cell.sd-box-bottom{border-bottom:2px solid var(--sd-heavy)}#wb-sudoku-fullscreen .sd-cell.fixed{color:var(--sd-ink);font-weight:650}#wb-sudoku-fullscreen .sd-cell.peer{background:var(--sd-peer)}#wb-sudoku-fullscreen .sd-cell.same{background:var(--sd-same)}#wb-sudoku-fullscreen .sd-cell.selected{background:var(--sd-selected);box-shadow:inset 0 0 0 2px var(--sd-accent);z-index:1}#wb-sudoku-fullscreen .sd-cell.wrong{color:var(--sd-error);background:var(--sd-error-bg);text-decoration:underline;text-decoration-thickness:2px;text-underline-offset:4px}#wb-sudoku-fullscreen .sd-cell.hinted{box-shadow:inset 0 0 0 2px #b47b16;background:#f9e9b9;color:#403619}
.sd-notes{position:absolute;inset:2px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));grid-template-rows:repeat(3,minmax(0,1fr));font-size:clamp(8px,calc(var(--sd-cell-font,23px) * .40),13px);font-weight:550;color:var(--sd-muted)}.sd-notes span{display:grid;place-items:center;line-height:1}.sd-notes span.matching{color:var(--sd-accent);font-weight:850;border-radius:3px;background:var(--sd-same)}
.sd-progress{border-radius:3px;background:var(--sd-line);overflow:hidden}.sd-progress i{display:block;height:100%;background:var(--sd-accent)}.sd-controls{min-width:0;display:grid;gap:12px}.sd-context{text-align:center;min-height:17px;color:var(--sd-muted);font-size:12px;line-height:1.4}.sd-tools{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:5px}
#wb-sudoku-fullscreen .sd-tool{border:1px solid transparent;background:transparent;border-radius:10px;min-height:51px;padding:5px 1px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px}.sd-icon{display:grid;place-items:center}.sd-icon svg{display:block;width:24px;height:24px}.sd-round .sd-icon svg{width:26px;height:26px}.sd-tool .sd-icon{line-height:1}.sd-tool .sd-label{font-size:11px;line-height:1.3;white-space:normal;text-align:center}#wb-sudoku-fullscreen .sd-tool.active{background:var(--sd-selected);border-color:var(--sd-accent);color:var(--sd-accent)}#wb-sudoku-fullscreen button:disabled{opacity:.34;cursor:default}.sd-keypad{display:grid;grid-template-columns:repeat(9,minmax(0,1fr));gap:5px}
#wb-sudoku-fullscreen .sd-number{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;background:var(--sd-wash);color:var(--sd-accent);border:1px solid var(--sd-line);border-radius:10px;min-height:58px;min-width:0;padding:4px 0;font-size:25px;font-weight:650}.sd-number small{font-size:10px;color:var(--sd-muted);font-weight:500}#wb-sudoku-fullscreen .sd-number.active{outline:2px solid var(--sd-accent);background:var(--sd-selected)}#wb-sudoku-fullscreen .sd-number.exhausted{opacity:.45}#wb-sudoku-fullscreen .sd-number:active,#wb-sudoku-fullscreen .sd-tool:active{background:var(--sd-selected)}
.sd-bottom{display:flex;justify-content:space-between;gap:12px}#wb-sudoku-fullscreen .sd-link{background:transparent;border:0;padding:8px 3px;min-height:40px;font-size:12px;color:var(--sd-accent);text-decoration:underline;text-underline-offset:4px}
.sd-mask{position:absolute;inset:0;z-index:5;display:grid;place-items:center;background:#1021278a;padding:20px;overflow:auto;touch-action:pan-y}.sd-dialog{width:min(100%,420px);max-height:100%;overflow:auto;background:var(--sd-surface);border:1px solid var(--sd-line);border-radius:22px;padding:24px;color:var(--sd-ink);box-shadow:0 16px 56px #00191f33}.sd-dialog h2{font-size:23px;margin:0 0 14px;line-height:1.3}.sd-dialog p{font-size:14px;line-height:1.8;color:var(--sd-muted);white-space:pre-line;margin:10px 0}.sd-dialog-actions{display:grid;gap:10px;margin-top:20px}#wb-sudoku-fullscreen .sd-dialog-button{min-height:46px;padding:11px 15px;border:1px solid var(--sd-line);border-radius:11px;background:var(--sd-wash);color:var(--sd-ink);font-size:14px}#wb-sudoku-fullscreen .sd-dialog-button.primary{background:var(--sd-accent);color:var(--sd-surface);border-color:var(--sd-accent);font-weight:650}.sd-option{display:flex;align-items:center;gap:14px;padding:14px 0;border-bottom:1px solid var(--sd-line)}.sd-option span{flex:1}.sd-option strong{display:block;font-size:14px}.sd-option small{display:block;color:var(--sd-muted);font-size:12px;line-height:1.6;margin-top:5px}.sd-option input{width:23px;height:23px;accent-color:var(--sd-accent);flex:none;cursor:pointer}.paused .sd-grid{visibility:hidden}
@media(orientation:landscape) and (min-width:550px){#wb-sudoku-fullscreen .sd-head{padding:4px 16px;grid-template-columns:44px 1fr 44px}.sd-heading h1{font-size:19px}.sd-heading small{display:none}#wb-sudoku-fullscreen .sd-layout{max-width:1120px;grid-template-columns:minmax(0,1fr) minmax(220px,.7fr);grid-template-rows:minmax(0,1fr);gap:25px;padding:9px 24px}.sd-board-area{gap:5px}.sd-meta{font-size:11px}.sd-difficulty{padding:3px 8px}.sd-controls{align-content:center;gap:8px}.sd-tools{grid-template-columns:repeat(6,minmax(0,1fr));gap:3px}.sd-tool .sd-label{font-size:10px}#wb-sudoku-fullscreen .sd-tool{min-height:46px}.sd-keypad{grid-template-columns:repeat(3,minmax(0,1fr));gap:5px}#wb-sudoku-fullscreen .sd-number{min-height:38px;flex-direction:row;font-size:23px;gap:12px}.sd-context{font-size:11px}.sd-dialog{padding:19px 22px}.sd-dialog-actions{margin-top:14px}.sd-bottom .sd-link{padding:3px;min-height:33px}}
@media(max-width:355px){#wb-sudoku-fullscreen .sd-layout{padding:8px 8px 10px;gap:8px}.sd-keypad{gap:3px}.sd-tool .sd-label{font-size:10px}.sd-heading small{font-size:9px}.sd-controls{gap:7px}#wb-sudoku-fullscreen .sd-number{min-height:52px}.sd-dialog{padding:18px}}
@media(max-height:650px) and (orientation:portrait){#wb-sudoku-fullscreen .sd-head{padding:4px 12px}.sd-heading small{display:none}#wb-sudoku-fullscreen .sd-layout{gap:6px;padding-top:6px;padding-bottom:6px}.sd-board-area{gap:5px}.sd-controls{gap:5px}.sd-bottom .sd-link{min-height:30px;padding:3px}.sd-context{font-size:11px}#wb-sudoku-fullscreen .sd-number{min-height:47px}}
`;
