name: Nookcade
options:
  bundleIdPrefix: io.github.jacklee992
  deploymentTarget:
    iOS: '17.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    TARGETED_DEVICE_FAMILY: '1,2'
    MARKETING_VERSION: '1.3.1'
    CURRENT_PROJECT_VERSION: '5'
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: 'YES'
targets:
  Nookcade:
    type: application
    platform: iOS
    sources:
      - path: Nookcade
      - path: build/www
        type: folder
        buildPhase: resources
    settings:
      base:
        DEVELOPMENT_TEAM: 5BG4VDJKTY
        PRODUCT_BUNDLE_IDENTIFIER: io.github.jacklee992.wanba.ios
        INFOPLIST_FILE: Nookcade/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  NookcadeTests:
    type: bundle.unit-test
    platform: iOS
    sources: [NookcadeTests]
    dependencies: [{target: Nookcade}]
    settings:
      base:
        DEVELOPMENT_TEAM: 5BG4VDJKTY
        GENERATE_INFOPLIST_FILE: 'YES'
  NookcadeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [NookcadeUITests]
    dependencies: [{target: Nookcade}]
    settings:
      base:
        DEVELOPMENT_TEAM: 5BG4VDJKTY
        GENERATE_INFOPLIST_FILE: 'YES'
schemes:
  Nookcade:
    build:
      targets:
        Nookcade: all
    test:
      targets: [NookcadeTests, NookcadeUITests]
